### ISSUE TITLE
Adas empty

### ISSUE THREAD

**Issue by bhack** [Itseez/opencv_contrib#102]
Why adas module has adas.cpp and its header empty? We have also got many stability issue on training varying samples size, number of feature and weak counter.

**Comment by tomrunia** [comment]
I have a similar question with regard to the use of Integral Channel Features for object detection. My goal is to use it for car detection on highways. Having obtained a nice dataset I am training the classifier using ICF but unfortunately I am also experiencing that the detector is highly unstable to the parameters (feature_count, weak_count). My original question was posted over here: http://answers.opencv.org/question/56263/integral-channel-feature-detector-for-cars-bad-results/ but I got the advise to try here as well :-) 

Does anyone have some good ideas of how to set the parameters?

**Comment by mshabunin** [comment]
The adas module has been removed during latest GSoC, thus considering issue invalid.
