### ISSUE TITLE
[Request] Release tag for corresponding OpenCV release

### ISSUE THREAD

**Issue by thorikawa** [Itseez/opencv_contrib#107]
Currently there is no tag/branch in opencv_contrib, which makes it hard to identify which commit to build with specific opencv version. For example, opencv_contrib (master branch as of Oct 1st, 2014) cannot be built with opencv-3.0.0-alpha. Please consider add release tag for opencv_contrib as well as opencv.

**Comment by StevenPuttemans** [comment]
@mshabunin Actually there are currently tags for OpenCV_contrib as I just checked. This can be closed down.
