### ISSUE TITLE
floor/ceil functions in motionSaliencyBinWangApr2014.cpp

### ISSUE THREAD

**Issue by ilkedemir** [Itseez/opencv_contrib#124]
VS2010 build complains about the floor and ceil functions having ambiguous input types. The parameters need to be explicitly casted.

**Comment by fpuja** [comment]
I solved it by adding the cast in the only two places where it was missing. Thanks for reporting the issue.

**Comment by StevenPuttemans** [comment]
@mshabunin this is solved, can be closed down. All the specific casts are already there. BTW --> if there is a way of giving me rights to manage this a bit like I did on the other dev page, feel free to do so.
