### ISSUE TITLE
descriptor.hpp and types.hpp needs inttypes.h

### ISSUE THREAD

**Issue by ilkedemir** [Itseez/opencv_contrib#125]
Although inttypes.h is a part of C99, VS2010 (and also 2005?) does not come with it. However descriptor.hpp and types.hpp explicitly need inttypes.h (independent of the "HAVE_INTTYPES_H" flag in cvconfig.h).

It would be better to either include inttypes.h as a source file, or make it optional based on HAVE_INTTYPES_H.

I believe the VS impl of inttypes.h can be found here: https://code.google.com/p/msinttypes/downloads/detail?name=msinttypes-r26.zip&can=2&q=

**Comment by StevenPuttemans** [comment]
This has been merged. @mshabunin this can be closed down.
