### ISSUE TITLE
problem while installation

### ISSUE THREAD

**Issue by ruthvik92** [Itseez/opencv_contrib#165]
cmake -DOPENCV_EXTRA_MODULES_PATH=/home/iiith/Desktop/Vision/opencv_contrib/modules  -DBUILD_opencv_bioinspired=OFF -DBUILD_opencv_adas=OFF -DBUILD_opencv_bgsegm=OFF -DBUILD_opencv_ccalib=OFF -DBUILD_opencv_datasets=OFF -DBUILD_opencv_datasetstools=OFF -DBUILD_opencv_face=OFF -DBUILD_opencv_latentsvm=OFF -DBUILD_opencv_line_descriptor=OFF -DBUILD_opencv_matlab=OFF -DBUILD_opencv_optflow=OFF -DBUILD_opencv_reg=OFF -DBUILD_opencv_rgbd=OFF -DBUILD_opencv_saliency=OFF -DBUILD_opencv_surface_matching=OFF -DBUILD_opencv_text=OFF -DBUILD_opencv_tracking=OFF -DBUILD_opencv_xfeatures2d=OFF -DBUILD_opencv_stitching=OFF -D BUILD_NEW_PYTHON_SUPPORT=OFF /usr/share ..

I tried to run this make command
after that 

make -j5

Output was .......
Note: Class Feature2D has more than 1 base class (not supported by Python C extensions)
      Bases:  cv::FeatureDetector, cv::DescriptorExtractor
      Only the first base class will be used
Generator error: the class for method createSuperpixelSEEDS is missing
make[2]: *** [modules/python2/pyopencv_generated_include.h] Error 255
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make: *** [all] Error 2

si i am not able to install opencv_cintrib

**Comment by Leo-8991** [comment]
Hello, 
I have encountered the same error, please let me know the environment to run this module.
Thank you.

**Comment by StevenPuttemans** [comment]
`Generator error: the class for method createSuperpixelSEEDS is missing` actually means that there was no python wrapper for that function. However there is a CV_EXPORTS availble now so this problem should be fixed --> https://github.com/StevenPuttemans/opencv_contrib/blob/master/modules/ximgproc/src/seeds.cpp#L187 

@mshabunin also fixed, you can close

**Comment by resplendent-star** [comment]
> `Generator error: the class for method createSuperpixelSEEDS is missing` actually means that there was no python wrapper for that function. However there is a CV_EXPORTS availble now so this problem should be fixed --> https://github.com/StevenPuttemans/opencv_contrib/blob/master/modules/ximgproc/src/seeds.cpp#L187
> 
> @mshabunin also fixed, you can close

hello,could plz tell me how to settle this problem? I am a fresh man ,dont know what your point
