### ISSUE TITLE
CMake Error: Target "opencv_modules" of type UTILITY may not be linked into another   target.

### ISSUE THREAD

**Issue by ultra-sonic** [Itseez/opencv_contrib#175]
Hello there,

i tried compiling opencv with opencv_contrib and it failed during cmake with the following error:
	CMake Error at cmake/OpenCVUtils.cmake:753 (target_link_libraries):
	  Target "opencv_modules" of type UTILITY may not be linked into another
	  target.  One may link only to STATIC or SHARED libraries, or to executables
	  with the ENABLE_EXPORTS property set.
	Call Stack (most recent call first):
	  modules/python/common.cmake:68 (ocv_target_link_libraries)
	  modules/python/python2/CMakeLists.txt:19 (include)

I'm on Centos 7.0 - cmake version 2.8.11
i tried on master and tag/3.0.0-beta
Let me know if you need further information!

BTW: I am not very familiar with cmake yet so please excuse me if this an easy problem to solve!

thanks in advance
Oliver

**Comment by mshabunin** [comment]
Provide path to `opencv_contrib/modules` not to `opencv_contrib`, like this:
```{.sh}
cmake ../opencv -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules
```

**Comment by ultra-sonic** [comment]
ok.....that was too easy!
Thank you very much!
