### ISSUE TITLE
cannot install contrib modules

### ISSUE THREAD

**Issue by howtobeahacker** [Itseez/opencv_contrib#177]
Hi all,
I tried to install Saliency module from contrib modules. I read the documents and tried Cmake commands as follows:
cmake -D CMAKE_BUILD_TYPE=Debug -D CMAKE_INSTALL_PREFIX=~/local -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules/ -D BUILD_DOCS=ON -D BUILD_EXAMPLES=ON -D WITH_CUDA=ON ..

After building, I cannot find saliency libraries or include files. It seems that my installation does not compile any contrib modules. 
Thank you for your regards.

**Comment by mshabunin** [comment]
Haven't you forget to run `make install` command? Without it, files will not be copied to the dir pointed by `CMAKE_INSTALL_PREFIX` option. Make sure you have _opencv_contrib_ repository in folder pointed by `OPENCV_EXTRA_MODULES_PATH` option (`../opencv_contrib`), no error will be shown if it is not found.
Also, please check your cmake output, the block starting with:
```
--   OpenCV modules:
--     To be built: ...
```

**Comment by howtobeahacker** [comment]
Thank @mshabunin . I made a mistake in OPENCV_EXTRA_MODULES_PATH, and I tried it several times with the same mistake. Sure, I did execute make install.
