### ISSUE TITLE
Error make openCV 3.0beta + extra modules [MacOSX 10.10]

### ISSUE THREAD

**Issue by andrea9lli** [Itseez/opencv_contrib#179]
Hi all, 
I tried to install openCV with extra modules on my macbook with Yosemite. The build phase is ok, using
$ cmake -DOPENCV_EXTRA_MODULES_PATH=<opencv_contrib>/modules 
but the make fails giving this errors:

Scanning dependencies of target opencv_face
[ 73%] Building CXX object modules/face/CMakeFiles/opencv_face.dir/src/eigen_faces.cpp.o
In file included from /local/opencv_contrib/modules/face/src/eigen_faces.cpp:19:
In file included from /local/opencv_contrib/modules/face/src/face_basic.hpp:4:
In file included from /local/opencv_contrib/modules/face/include/opencv2/face.hpp:358:
/local/opencv_contrib/modules/face/include/opencv2/face/facerec.hpp:23:27: error: unknown type name 'NumComponents'
    CV_PURE_PROPERTY(int, NumComponents)
                          ^
/local/opencv_contrib/modules/face/include/opencv2/face/facerec.hpp:23:5: error: C++ requires a type specifier for all declarations
    CV_PURE_PROPERTY(int, NumComponents)
    ^~~~~~~~~~~~~~~~
/local/opencv_contrib/modules/face/include/opencv2/face/facerec.hpp:23:41: error: expected ';' at end of declaration list
    CV_PURE_PROPERTY(int, NumComponents)
                                        ^
                                        ;
/local/opencv_contrib/modules/face/include/opencv2/face/facerec.hpp:98:27: error: unknown type name 'GridX'
    CV_PURE_PROPERTY(int, GridX)
                          ^
/local/opencv_contrib/modules/face/include/opencv2/face/facerec.hpp:98:5: error: C++ requires a type specifier for all declarations
    CV_PURE_PROPERTY(int, GridX)
    ^~~~~~~~~~~~~~~~
/local/opencv_contrib/modules/face/include/opencv2/face/facerec.hpp:98:33: error: expected ';' at end of declaration list
    CV_PURE_PROPERTY(int, GridX)
                                ^
                                ;
In file included from /local/opencv_contrib/modules/face/src/eigen_faces.cpp:19:
/local/opencv_contrib/modules/face/src/face_basic.hpp:156:27: error: C++ requires a type specifier for all declarations
    CV_IMPL_PROPERTY(int, NumComponents, _num_components)
                          ^~~~~~~~~~~~~
/local/opencv_contrib/modules/face/src/face_basic.hpp:156:42: error: unknown type name '_num_components'
    CV_IMPL_PROPERTY(int, NumComponents, _num_components)
                                         ^
/local/opencv_contrib/modules/face/src/face_basic.hpp:156:5: error: C++ requires a type specifier for all declarations
    CV_IMPL_PROPERTY(int, NumComponents, _num_components)
    ^~~~~~~~~~~~~~~~
/local/opencv_contrib/modules/face/src/face_basic.hpp:156:58: error: expected ';' at end of declaration list
    CV_IMPL_PROPERTY(int, NumComponents, _num_components)
                                                         ^
                                                         ;
/local/opencv_contrib/modules/face/src/face_basic.hpp:114:11: error: member initializer '_num_components' does not name a non-static data member or base class
        : _num_components(num_components), _threshold(threshold)
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/local/opencv_contrib/modules/face/src/face_basic.hpp:120:33: error: use of undeclared identifier '_num_components'
        fs["num_components"] >> _num_components;
                                ^
/local/opencv_contrib/modules/face/src/face_basic.hpp:143:35: error: use of undeclared identifier '_num_components'
        fs << "num_components" << _num_components;
                                  ^
/local/opencv_contrib/modules/face/src/eigen_faces.cpp:87:9: error: use of undeclared identifier '_num_components'
    if((_num_components <= 0) || (_num_components > n))
        ^
/local/opencv_contrib/modules/face/src/eigen_faces.cpp:87:35: error: use of undeclared identifier '_num_components'
    if((_num_components <= 0) || (_num_components > n))
                                  ^
/local/opencv_contrib/modules/face/src/eigen_faces.cpp:88:9: error: use of undeclared identifier '_num_components'
        _num_components = n;
        ^
/local/opencv_contrib/modules/face/src/eigen_faces.cpp:91:44: error: use of undeclared identifier '_num_components'
    PCA pca(data, Mat(), PCA::DATA_AS_ROW, _num_components);
                                           ^
17 errors generated.
make[2]: *** [modules/face/CMakeFiles/opencv_face.dir/src/eigen_faces.cpp.o] Error 1
make[1]: *** [modules/face/CMakeFiles/opencv_face.dir/all] Error 2
make: *** [all] Error 2

Can you help me please?

**Comment by mshabunin** [comment]
Can you, please, provide cmake output (via gist on github, for example)?

**Comment by andrea9lli** [comment]
https://gist.github.com/andrea9lli/0e789912103341bdf670#file-gistfile1-txt

**Comment by mshabunin** [comment]
Please, try to run the build in clean directory, if it does not help, run the build with cmake `-DBUILD_opencv_face=OFF` option to disable this module temporarily and see if other modules have similar problems.

**Comment by Dikay900** [comment]
if you use opencv beta which not contains the removal of the algorithm factory you will get such errors. Maybe try the current master branch of the opencv main repo?
opencv main beta + current opencv_contrib won't work

**Comment by andrea9lli** [comment]
I tried to add -DBUILD_opencv_face=OFF to cmake, but it does fail again. This time on edge_filter.hpp, but the error is the same

**Comment by mshabunin** [comment]
@andrea9lli, now I see, @Dikay900  is right. You should take the latest version from OpenCV `master` branch to buld with _contrib_.

**Comment by StevenPuttemans** [comment]
this one can also be closed down --> is not a bug but a wrong version that is being built
