### ISSUE TITLE
Wrong angles in acffeature.cpp:computeChannels

### ISSUE THREAD

**Issue by carka684** [Itseez/opencv_contrib#188]
cartToPolar return angles between (0,360) but this function works around cartToPolar returning (-180,180)

**Comment by StevenPuttemans** [comment]
Can you please check if this is still the case for your code and provide a sample please? Because I have it running right here without any problems and returning angles correctly.

**Comment by carka684** [comment]
Can't test the code at the moment but this fix https://github.com/Itseez/opencv_contrib/commit/d76b976012cf47eb90720b1cd6a06fa664f20425#diff-64782f0669713a552a2e3c9c2f61524c should have fixed it.

**Comment by StevenPuttemans** [comment]
:+1: then this should be closed down :)

**Comment by carka684** [comment]
Yep! Hadn't seen that commit :+1:
