### ISSUE TITLE
Moving latentsvm test data into opencv_extra

### ISSUE THREAD

**Issue by Jiaolong** [Itseez/opencv_contrib#191]
Hi, I just noticed the test data of latentsvm are in opencv_contrib, under the module [folder] (https://github.com/Itseez/opencv_contrib/tree/master/modules/latentsvm/testdata/latentsvm)

Should we move the data into opencv_extra? In fact, after building opencv, the `opencv_test_latentsvmdetector` can not find these testing data.

**Comment by Jiaolong** [comment]
I have already sent two pull requests to solve this issue.

**Comment by StevenPuttemans** [comment]
As far as I can see the path location of the data has been solved. So this could be closed unless we want to wait until the data is pushed to the extra folder.
