### ISSUE TITLE
About the naming of LatentSVM detector in opencv

### ISSUE THREAD

**Issue by Jiaolong** [Itseez/opencv_contrib#193]
Hi, I suggest to change the name of **LatentSVM** detector into **DPM** detector. As we know, latent svm refers to the training process of the **deformable part-based model (DPM)** but not testing. Currently, we haven't provided the training code of DPM in opencv, i.e., we acutally don't  have a **latent svm** in opencv. :smile:

**Comment by StevenPuttemans** [comment]
As it seems you are doing a GSoC to overcome this, I think this issue can be closed down for clarity reasons --> https://github.com/Itseez/opencv_contrib/pull/286

**Comment by Jiaolong** [comment]
Thanks for reminding this. :)
