### ISSUE TITLE
cannot build opencv with modules

### ISSUE THREAD

**Issue by techfort** [Itseez/opencv_contrib#194]
Hi there

thanks for the great work on opencv! I'm facing the following problem
Linking CXX shared library ../../lib/libopencv_xobjdetect.so
/usr/bin/ld: cannot find -lWRAP
/usr/bin/ld: cannot find -lpython
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libopencv_xobjdetect.so.3.0.0] Error 1
make[1]: *** [modules/xobjdetect/CMakeFiles/opencv_xobjdetect.dir/all] Error 2
make: *** [all] Error 2

any ideas?

**Comment by mshabunin** [comment]
@techfort, you need to update _opencv_ repository to the latest version to build latest _opencv_contrib_ with it, current _opencv_contrib_ version is not compatible with 3.0.0-beta (which you are probably using). Or checkout _opencv_contrib_ near 2014-11-10.
See also similar issue #179.

**Comment by techfort** [comment]
Ok thank you - building the library worked. However, I'm getting an error on the python bindings, (no attribute createEigenFaceRecognizer). I built opencv with this command:
```bash
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON USE_EIGEN=/usr/include/eigen3 -D OPENCV_EXTRA_MODULES_PATH=/home/d3athmast3r/dev/opencv_contrib/modules ..
```
Any ideas? sorry for extending the problem.

**Comment by mshabunin** [comment]
Are you sure you used the _face_ submodule:
```.py
import cv2
f = cv2.face.createEigenFaceRecognizer()
```
However, the created object does not have any methods. This is also known issue #184.

**Comment by techfort** [comment]
Hi Maksim, thank you for clarifying about submodules.
The script now complains about the lack of a 'train' attribute, if there was any official documentation about this I would educate myself, I don't want to bug you every step of the way :)

**Comment by mshabunin** [comment]
>lack of a 'train' attribute

@techfort, this is the issue I mentioned (#184):

>created object does not have any methods

Unfortunately _face_ module python wrappers are broken at this moment. You can try to build an earlier version (middle of February 2015) or wait until it will be fixed or fix it by yourself.
Just don't forget to use _opencv_ and _opencv_contrib_ versions from the same time moment if you choose the first variant.

**Comment by techfort** [comment]
ok thank you. I'll watch the repo for releases. Thanks for your help!

**Comment by techfort** [comment]
Maksim, by version do you just mean any commit from Mid-February? I don't see branches or tags so I have no reference point. A particular commit for both opencv and contrib would be great! Thanks for your help.

**Comment by mshabunin** [comment]
@techfort, yes, I meant any commit. Just call something like:
```.sh
git checkout `git rev-list -n1 --before="2015-2-10" master`
```
in each directory (_opencv_ and _opencv_contrib_).

**Comment by techfort** [comment]
i checked out according to instructions, now i get this:

import cv2

ImportError: /usr/local/lib/python2.7/dist-packages/cv2.so: undefined symbol: _ZN2cv2ml21NormalBayesClassifier6createEv

Sorry for the nagging, but I'm a bit stuck on this.

**Comment by mshabunin** [comment]
Have you tried to run it without install:
```.sh
# suppose you are in the build directory
make opencv_python2
export PYTHONPATH=lib
python2
```
... then:
```.py
>>> import cv2
>>> f = cv2.face.createEigenFaceRecognizer()
```
It worked for me.
Also you can try to make clean build.

**Comment by techfort** [comment]
Hi Maksim, would it be possible to continue this through email? I don't want to pollute your issues. Otherwise I'll keep posting here, let me know.

**Comment by mshabunin** [comment]
@techfort, I think the [QA forum](http://answers.opencv.org/questions/) is more appropriate for this kind of questions. Post your issues there and the community will try to help.

**Comment by techfort** [comment]
Sure thanks. You can close this.

**Comment by arunssundar** [comment]
import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/python2.7/site-packages/cv2.so: undefined symbol: _ZN2cv14setWindowTitleERKNS_6StringES2_

I'm facing this error.. what to do? Stuck in this for 2 days.

**Comment by alalek** [comment]
@arunssundar Do you have build problem or something else?

**Comment by arunssundar** [comment]
Yeah. While building open cv 3.0 with python 2.7.

**Comment by LPCelite** [comment]
@techfort 
I get the same problem: 
import cv2
ImportError: /usr/local/lib/python2.7/dist-packages/cv2.so: undefined symbol: _ZN2cv2ml21NormalBayesClassifier6createEv 

Have you sloved this problem???
Thanks.

**Comment by mshabunin** [comment]
@LPCelite , looks like you are using OpenCV package installed via pip, or conflicting OpenCV version installed in the system. 
Did you try to build OpenCV with Python support by yourself?

**Comment by LPCelite** [comment]
I build OpenCV by Cmake and it contains python.
OpenCV works fine with C++, but get wrong with python.
can you help me?

**Comment by alalek** [comment]
Check change date of this file.
Check paths from `ldd /usr/local/lib/python2.7/dist-packages/cv2.so` output.
Remove this file and rebuild OpenCV
Find fresh cv2.so and setup PYTHONPATH

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by LPCelite** [comment]
Thanks, i make some changes as follows:
sudo rm usr/local/lib/python2.7/dist-package/cv2.so
 sudo apt-get install python-opencv

import cv2
print cv2.__version__
That works fine, the version of opencv for python is 2.4.9. it's enough for me.
