### ISSUE TITLE
structured edge detection segfaults on certain images

### ISSUE THREAD

**Issue by raghuramos1987** [Itseez/opencv_contrib#195]
When used with images of size 400x225 (wxh) there is a segfault in gradientHist. It looks like heights of 225, 213, 201 fail.

**Comment by Dikay900** [comment]
please provide an image and the code to reproduce the problem.

**Comment by raghuramos1987** [comment]
![img_sc](https://cloud.githubusercontent.com/assets/740085/6812545/e3609e92-d22c-11e4-8c6e-8ba57d6be03e.jpg)


https://gist.github.com/raghuramos1987/ae784241d8b2f6a9483c is the driver program. It needs the image and the model file from structured edge detection.

**Comment by raghuramos1987** [comment]
This looks like an issue with cvRound in gradientHist where the histogram matrix is created. On some numbers it gets rounded down which ends up writing parts into memory blocks which shouldnt be accessed.

 histogram.create( cv::Size( cvRound(src.size().width/float(pSize)),
cvRound(src.size().height/float(pSize)) ),

if src has odd numbered sizes this round can fail to allocate the required size. It should ideally be cvCeil but I dont know if that has any repurcussions on the algorithm itself. (From what I understood in the paper it shouldnt). I can put up a pull request if the original author confirms that this is the case.

**Comment by mshabunin** [comment]
@raghuramos1987, can you, please, provide your cmake output (the part with platform, compiler, configuration)? 

Have you tried to reproduce the issue with `cvRound` only?
```.cpp
const int width = <?>;
const int height = <?>;
const int sz = <?>;
cout << cvRound(width/float(sz)) << ", " << cvRound(height/float(sz)) << endl;
```

**Comment by raghuramos1987** [comment]
Yup

This is the result


    const int width = 241;                                                                            
    const int height = 400;                                                                           
    const int sz = 2;                                                                                 
    std::cout << cvRound(width/float(sz)) << ", " << cvRound(height/float(sz)) << std::endl;

120, 200

**Comment by mshabunin** [comment]
@raghuramos1987, cvRound can not produce same results on all platforms, one should not rely on it's output for such tasks. I'd recommend to use cvCeil in this case to avoid invalid memory access.

Feel free to create pull request if this fix will help you.

**Comment by berak** [comment]
made a standalone test case here: https://gist.github.com/berak/9a556537dccea2709712

**Comment by mshabunin** [comment]
@berak, thank you for example. As I understand, changing to cvCeil helps, doesn't it? I can make pull request if it fixes the problem (the issue is still can not be reproduced on my machine).

**Comment by berak** [comment]
yes it does. made https://github.com/Itseez/opencv_contrib/pull/274 already

**Comment by mshabunin** [comment]
Considering it done
