### ISSUE TITLE
FR_lfw::load() is not implemented

### ISSUE THREAD

**Issue by rmekdma** [Itseez/opencv_contrib#198]
fr_lfw.cpp has its implementation in FR_lfwImp::load().
The author seems to forget to add it to FR_lfw::load().
This cause segmentation fault during execution of fr_lfw_benchmark.cpp.

**Comment by avdmitry** [comment]
FR_lfw::create() returns instance of FR_lfwImp, which actualy do the job.
The cause of your crash somewhere else, I can suppose that you do something wrong with data.
Please, see usage here: http://docs.opencv.org/3.0-last-rst/modules/datasets/doc/fr_lfw.html
