### ISSUE TITLE
Can't build with opencv-3.0.0 on Linux - Unknown CMake command "ocv_include_modules_recurse".

### ISSUE THREAD

**Issue by b-filip** [Itseez/opencv_contrib#212]
I am trying to build opencv with these extra modules, but CMake fails to generate Makefiles.

I run the following command

```
cmake ../opencv -DCMAKE_BUILD_TYPE=Debug -DWITH_QT=ON -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules -G "Unix Makefiles"
```

and get the following error:

```
CMake Error at /home/crabman/projects/vk_person_photos/opencv_contrib/modules/adas/tools/fcw_train/CMakeLists.txt:16 (ocv_include_modules_recurse):
  Unknown CMake command "ocv_include_modules_recurse".


-- Configuring incomplete, errors occurred!
```

**Comment by mshabunin** [comment]
Please, use the latest _opencv_ version to build the latest _opencv_contrib_.

**Comment by b-filip** [comment]
opencv-3.0 beta is the latest version available on http://opencv.org/downloads.html and that's what I am using

**Comment by mshabunin** [comment]
@b-filip, then you should use https://github.com/Itseez/opencv_contrib/tree/3.0.0-beta version of _opencv_contrib_.

**Comment by b-filip** [comment]
That resolved my problem with cmake, thanks.
