### ISSUE TITLE
fatal error: opencv2/ts/ts.hpp: No such file or directory - on the tag 3.0.0-beta 

### ISSUE THREAD

**Issue by b-filip** [Itseez/opencv_contrib#213]
I have opencv-3.0.0-beta downloaded and opencv_contrib checked out at the tag 3.0.0-beta.

```
~/projects/vk_person_photos/opencv_build_gcc> git -C ../opencv_contrib/ status
HEAD detached at 3.0.0-beta
nothing to commit, working directory clean
```

CMake creates the Makefile successfully with the following command

```
cmake ../opencv-3.0.0-beta/ -DCMAKE_BUILD_TYPE=Debug -DWITH_QT=ON -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules -G "Unix Makefiles"
```

But the building process (make) fails with this error:

```
[ 34%] Building CXX object modules/cvv/CMakeFiles/opencv_test_cvv_pch_dephelp.dir/opencv_test_cvv_pch_dephelp.cxx.o
In file included from /home/crabman/projects/vk_person_photos/opencv_build_gcc/modules/cvv/opencv_test_cvv_pch_dephelp.cxx:1:0:
/home/crabman/projects/vk_person_photos/opencv_contrib/modules/cvv/test/test_precomp.hpp:14:29: fatal error: opencv2/ts/ts.hpp: No such file or directory
 #include <opencv2/ts/ts.hpp>
                             ^
compilation terminated.
modules/cvv/CMakeFiles/opencv_test_cvv_pch_dephelp.dir/build.make:64: recipe for target 'modules/cvv/CMakeFiles/opencv_test_cvv_pch_dephelp.dir/opencv_test_cvv_pch_dephelp.cxx.o' failed
```

And indeed, there is a file *ts.hpp* in *opencv-3.0.0-beta/modules/ts/include/opencv2/ts.hpp*, but it's not in *ts* directory as written in include.

**Comment by mshabunin** [comment]
@b-filip, it seems that the _cvv_ module was broken in beta release. Please, use the latest _master_ branch versions of _opencv_ and  _opencv_contrib_ if you really need this module. Otherwise, add the `-DBUILD_opencv_cvv=OFF` option to cmake to disable it.

**Comment by b-filip** [comment]
That worked. Thanks for the help.
