### ISSUE TITLE
Reference to non-existent field 'rootfilters'

### ISSUE THREAD

**Issue by sam3891** [Itseez/opencv_contrib#222]
Hi,

When I run the script on 'person_final.mat' of VOC2010 models as:

mat2xml('person_final.mat','person.xml')

it give me the error:
Reference to non-existent field 'rootfilters'.

Please help me solve this error. Thank you.

**Comment by StevenPuttemans** [comment]
Actually since all the xml models are supplied for ensuring that OpenCV can work with them right here: https://github.com/Itseez/opencv_contrib/tree/master/modules/latentsvm/testdata/latentsvm/models_VOC2007_cascade

This can be closed down.

**Comment by mshabunin** [comment]
Looks like raw data files should be converted to structured format first.

This function can help: https://github.com/rbgirshick/voc-dpm/blob/master/star-cascade/grammar2simple.m As I can see, the output of this function will be compatible with the `mat2xml` function.

**Comment by StevenPuttemans** [comment]
Thanks for the link @mshabunin!
