### ISSUE TITLE
API consistency

### ISSUE THREAD

**Issue by techfort** [Itseez/opencv_contrib#226]
Hi! As usual thanks for the outstanding work on OpenCV and contrib.
Is it possible to consider moving FAST, BRIEF and ORB under `cv2.xfeatures2d` like SURF and SIFT are? Or is there a specific reason I'm missing why they are in `cv2` rather than the submodule. Thanks.

**Comment by ahundt** [comment]
I think SURF and SIFT may be restricted intellectual property while the others are not. Therefore, all unrestricted code is in features2d while restricted code is in xfeatures2d.

**Comment by techfort** [comment]
you're right, i noticed this a while ago. I guess i should have updated the ticket. Thanks!
