### ISSUE TITLE
OS X 10.10 with homebrew, error in opencv_contrib when Qt is enabled, particularly in cvv

### ISSUE THREAD

**Issue by ahundt** [Itseez/opencv_contrib#272]
I'm on OSX 10.10 installing via homebrew and compiling with clang. I'm running into compiler errors, which are detailed in the following homebrew issues, but turn out to be a problem with the underlying opencv_contrib:

[first homebrew issue 2391](https://github.com/Homebrew/homebrew-science/issues/2391) 
[second homebrew issue 2390](https://github.com/Homebrew/homebrew-science/issues/2390)

Here is the specific compiler error I'm encountering:

```
In file included from /tmp/opencv320150617-87721-1o80hb4/opencv-3.0.0/opencv_contrib/modules/cvv/src/controller/view_controller.cpp:12:
In file included from /tmp/opencv320150617-87721-1o80hb4/opencv-3.0.0/opencv_contrib/modules/cvv/src/controller/../gui/overview_panel.hpp:12:
/tmp/opencv320150617-87721-1o80hb4/opencv-3.0.0/opencv_contrib/modules/cvv/src/controller/../gui/../stfl/stfl_engine.hpp:1056:30: error: use 'template' keyword to treat 'value' as a dependent template name
                return settings.value(key).value<QStringList>();
                                           ^
                                           template 
```

Also note that [homebrew has been updated for opencv3.0](https://github.com/Homebrew/homebrew-science/pull/2398), and that is what i'm installing with the opencv_contrib components.

My specific install command in this case was

    ± brew install opencv3 --c++11 --with-cuda --with-contrib --with-tbb --with-qt5 --with-gstreamer --with-opengl --with-openni

Here is the related [homebrew gist containing detailed compilation logs](https://gist.github.com/f22d34bb08dcb942ae5f).

**Comment by willard-yuan** [comment]
I have installed OpenCV3.0 by Homebrew. I would to know if it is possible to install **opencv_contrib** with Homebrew, and how to do it?

**Comment by StevenPuttemans** [comment]
Hmm as far as I know OpenCV does not maintain those homebrew repos. You should rather just build the code from scratch using the provided repos.

**Comment by ahundt** [comment]
@willard-yuan 

    brew install opencv3 --c++11 --with-cuda --with-contrib --with-tbb --with-qt5 --with-gstreamer --with-opengl --with-openni --with-contrib

The key is that last `--with-contrib`.

@StevenPuttemans I'm not asking them to fix homebrew, but rather to fix opencv-contrib. Homebrew is how I'm providing a straightforward explanation of how to reproduce the problem. The `template` keyword as describe in the error is clearly missing.
