### ISSUE TITLE
surface_matching sample core dump in the case of no match results

### ISSUE THREAD

**Issue by buzziam** [Itseez/opencv_contrib#278]
opencv_contrib/modules/surface_matching/samples/ppf_load_match.cpp

A trivial problem - but one none-the-less (leading to unnecessary time spent) is that the result vector resulting from the match method on PPF3Detector may be of length(size) 0. This possibility is not taken into account in the sample code that follows. 

I'll fork, fix, and, create a pull request.

**Comment by bmagyar** [comment]
Hi,

Awesome! Thanks a lot!

**Comment by buzziam** [comment]
hello - no prob.

**Comment by buzziam** [comment]
drats - ulong should be size_t for other platforms - working...

**Comment by StevenPuttemans** [comment]
As far as I can see, the fix is merged and this can be closed down.

**Comment by bmagyar** [comment]
Yes. Let me put a reference of it here for the record #279

**Comment by StevenPuttemans** [comment]
:+1: then you can also close it down :P

**Comment by bmagyar** [comment]
I would if I could :) 

@vpisarev please assist us by closing this issue
