### ISSUE TITLE
Opencl_kernels*.hpp missing

### ISSUE THREAD

**Issue by zchen0211** [Itseez/opencv_contrib#281]
Try to build optical flow module, which contains a file modules/optflow/src/motempl.cpp.
When I build, it throws the error at #include "opencl_kernels_optflow.hpp".
I search the whole trunk but did not find this file.

**Comment by alalek** [comment]
Files `opencl_kernels_` are autogenerated.

Please provide more info about your build:
- git commit SHA hash (`git rev-parse HEAD`) for opencv & opencv_contrib repo
- used CMake options

**Comment by pkeir** [comment]
Could you point out the scripts which control the generation of the `opencl_kernels_` files?

**Comment by alalek** [comment]
It is in the main OpenCV repo: https://github.com/Itseez/opencv/blob/3.1.0/cmake/cl2cpp.cmake

Looks like this issue is not actual anymore and problem is a result of incorrect usage.

**Comment by xiaopengs** [comment]
how to generation it single
