### ISSUE TITLE
opencv_test_reg does not pass on clean Ubuntu 14.04 install

### ISSUE THREAD

**Issue by MrMallIronmaker** [Itseez/opencv_contrib#294]
In the most recent version of OpenCV, I was having some trouble with the image registration module. I checked the opencv_test_reg executable, and it failed with this information:
```
C++ exception with description "/home/mark/opencv/modules/imgproc/src/imgwarp.cpp:4670: error: (-215) _map1.size().area() > 0 in function remap" thrown in the test body.
```
This is on a virtual machine running Ubuntu 14.04 that I used specifically for this image registration OpenCV project. 

Is this likely to be an error on my machine or in the code? If it is in the code, how do I go about submitting the change back to this repository once I have found it?

**Comment by kurnianggoro** [comment]
if you want to submit a bug fix, you can follow these instructions
http://code.opencv.org/projects/opencv/wiki/How_to_contribute

**Comment by alfonsosanchezbeato** [comment]
@MrMallIronmaker to run the tests you need to copy the file "home.png" that is in $OPENCV_CONTRIB/modules/reg/samples/ to the place where you run the test executable from.

**Comment by MrMallIronmaker** [comment]
That's the correct fix! Thanks. Is there any reason the file is not automatically found or at least a useful error is given?
