### ISSUE TITLE
acffeature.cpp possible array index overflow

### ISSUE THREAD

**Issue by rookiepig** [Itseez/opencv_contrib#314]
// If angle == 180, prevent index overflow
            if (ind == 6)
                ind = 5;

When I am running this code, i get ind = 11, so should we change the if condition to if(ind >= 6) ?

**Comment by carka684** [comment]
No, you get ind = 11 because angle = 330 but it should be 0 < angle < 180. Have you the latest version with  https://github.com/Itseez/opencv_contrib/commit/d76b976012cf47eb90720b1cd6a06fa664f20425#diff-64782f0669713a552a2e3c9c2f61524c 
?

**Comment by rookiepig** [comment]
Thanks for your information. My is something like this:

```
      float angle = angles(row, col);
      if (angle < 0)
        angle += 180;
      int ind = (int)(angle / 30);
```
So this issue is closed.
