### ISSUE TITLE
Bioinspired `& requires l-value` on Windows

### ISSUE THREAD

**Issue by patricksnape** [Itseez/opencv_contrib#332]
I'm seeing an error [here](https://github.com/Itseez/opencv_contrib/blob/master/modules/bioinspired/src/transientareassegmentationmodule.cpp#L457):

``C2102: '&' requires l-value``

which seems to be about the first argument, `inputToSegment`.

I'm in the middle of creating conda packages for Python 2 and 3 on all platforms and I've got a set of patches that allow compilation on Windows, but I am not familiar enough with the code to remedy this. 

At the moment I am disabling the bioinspired module for my conda builds due to this. Any guidance on how to patch this would mean I can re-enable it!

**Comment by alalek** [comment]
We have no issues with compilation on Windows with MSVS 2013:
http://pullrequest.opencv.org/buildbot/builders/master-contrib-win64-vc12

**Comment by patricksnape** [comment]
I'm seeing this issue on both MSVC 2008 and 2010 which are required for Python 2.7 and Python 3.4 builds. If you are building the Python bindings with MSVC 2013 you may find that the whole Python interpreter crashes on actions such as file writing.

**Comment by patricksnape** [comment]
It looks to me like it has something to do with [this issue](http://stackoverflow.com/questions/6066273/pointer-into-vector-but-not-into-a-valarray) about the const'ness of valarray indexing.

**Comment by patricksnape** [comment]
Yes. It was because of that. As suggeseted [here](http://objectmix.com/c/40001-address-first-member-valarray.html), I performed a const_cast to fix the compilation issue. The patch to remedy this is given below.

```
--- modules\bioinspired\src\transientareassegmentationmodule.cpp
+++ modules\bioinspired\src\transientareassegmentationmodule.cpp
@@ -454,7 +454,7 @@
 
     // first square the input in order to increase the signal to noise ratio
     // get motion local energy
-    _squaringSpatiotemporalLPfilter(&inputToSegment[channelIndex*getNBpixels()], &_localMotion[0]);
+    _squaringSpatiotemporalLPfilter(&const_cast<std::valarray<float>&>(inputToSegment)[channelIndex*getNBpixels()], &_localMotion[0]);
 
     // second low pass filter: access to the neighborhood motion energy
     _spatiotemporalLPfilter(&_localMotion[0], &_neighborhoodMotion[0], 1);
```

**Comment by albenoit** [comment]
Hi,

it sounds strange to me that the error only appears here since such pointer
access is applied plenty of times in these codes.
I have to check it on linux version to see if code still runs fine on this
module with the proposed change.

However, what is recommended by the OpenCV team regarding such kind or
error and change ? It seems that the patch is addressed to old compiler
versions since recent versions do not need it. Then, what do you recommend ?

Thanks for suggestions.
Regards.
  Alex

2015-08-14 14:53 GMT+02:00 Patrick Snape <notifications@github.com>:

> Yes. It was because of that. As suggeseted here
> <http://objectmix.com/c/40001-address-first-member-valarray.html>, I
> performed a const_cast to fix the compilation issue. The patch to remedy
> this is given below.
>
> --- modules\bioinspired\src\transientareassegmentationmodule.cpp
> +++ modules\bioinspired\src\transientareassegmentationmodule.cpp
> @@ -454,7 +454,7 @@
>
>      // first square the input in order to increase the signal to noise ratio
>      // get motion local energy
> -    _squaringSpatiotemporalLPfilter(&inputToSegment[channelIndex*getNBpixels()], &_localMotion[0]);
> +    _squaringSpatiotemporalLPfilter(&const_cast<std::valarray<float>&>(inputToSegment)[channelIndex*getNBpixels()], &_localMotion[0]);
>
>      // second low pass filter: access to the neighborhood motion energy
>      _spatiotemporalLPfilter(&_localMotion[0], &_neighborhoodMotion[0], 1);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Itseez/opencv_contrib/issues/332#issuecomment-131096781>
> .
>



-- 
Alexandre BENOIT,
Associate Professor / Maître de Conférence
Image processing and visual scene classification,
LISTIC Lab / IUT Annecy
https://sites.google.com/site/benoitalexandrevision/

**Comment by patricksnape** [comment]
But these changes are required for Python compatibility. If you compile with a non-compliant (read newer as in VS2012 and above) compiler you are asking for trouble!

Also, this appears to be a very specific case of indexing a ``std::valarray`` on a const reference, which - perhaps in older implementations? - returns an rvalue rather than a reference. Thus, you cannot take the address. Although this is a strange case, it does actually highlight the fact that you are breaking the encapsulation of the valarray by grabbing a pointer to it - arguably you shouldn't do this.

**Comment by albenoit** [comment]
Yes, no doubt you are right.

did you push a change on opencv_contrib?

Thanks.
   Alex


2015-08-14 15:13 GMT+02:00 Patrick Snape <notifications@github.com>:

> But these changes are required for Python compatibility. If you compile
> with a non-compliant (read newer as in VS2012 and above) compiler you are
> asking for trouble!
>
> Also, this appears to be a very specific case of indexing a std::valarray
> on a const reference, which - perhaps in older implementations? - returns
> an rvalue rather than a reference. Thus, you cannot take the address.
> Although this is a strange case, it does actually highlight the fact that
> you are breaking the encapsulation of the valarray by grabbing a pointer to
> it - arguably you shouldn't do this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Itseez/opencv_contrib/issues/332#issuecomment-131101300>
> .
>



-- 
Alexandre BENOIT,
Associate Professor / Maître de Conférence
Image processing and visual scene classification,
LISTIC Lab / IUT Annecy
https://sites.google.com/site/benoitalexandrevision/
