### ISSUE TITLE
Error while make -j $(nproc)

### ISSUE THREAD

**Issue by kishorekumar29** [Itseez/opencv_contrib#333]
I cloned the repository and executed the line (cmake -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ..) successfully. When i tried "make -j $(nproc)" i got the following error

/home/robotics/opencv_contrib/modules/ximgproc/samples/disparity_filtering.cpp: In function ‘int main(int, char**)’:
/home/robotics/opencv_contrib/modules/ximgproc/samples/disparity_filtering.cpp:170:35: error: ‘MODE_SGBM_3WAY’ is not a member of ‘cv::StereoSGBM’
             left_matcher->setMode(StereoSGBM::MODE_SGBM_3WAY);
                                   ^
/home/robotics/opencv_contrib/modules/ximgproc/samples/disparity_filtering.cpp:235:30: error: ‘MODE_SGBM_3WAY’ is not a member of ‘cv::StereoSGBM’
             matcher->setMode(StereoSGBM::MODE_SGBM_3WAY);
                              ^
make[2]: *** [modules/ximgproc/CMakeFiles/example_ximgproc_disparity_filtering.dir/samples/disparity_filtering.cpp.o] Error 1
make[1]: *** [modules/ximgproc/CMakeFiles/example_ximgproc_disparity_filtering.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Built target opencv_test_xfeatures2d
make: *** [all] Error 2
robotics@robotics-desktop:~/opencv_dir/build$ 

Please help to get around this.

**Comment by alalek** [comment]
Update both opencv / opencv_contrib repositories, clean build directory and try again.

Some configurations are checked regularly and there are no build issues:
http://pullrequest.opencv.org/buildbot/waterfall?category=check-contribmaster

**Comment by dennisobrien** [comment]
I was experiencing the same error when I had opencv at 3.0.0 and opencv_contrib at the latest from github.  It was fixed by doing `git checkout 3.0.0` on both repos.
