### ISSUE TITLE
SURF setHessianThreshold Read-Only?

### ISSUE THREAD

**Issue by toddsampson** [Itseez/opencv_contrib#371]
I get the following when I attempt to set a Hessian Threshold:

```
>>> cv2.__version__
'3.0.0'
>>> img = cv2.imread('fly.png',0)
>>> surf = cv2.xfeatures2d.SURF_create(400)
>>> surf.setHessianThreshold = 500
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'cv2.xfeatures2d_SURF' object attribute 'setHessianThreshold' is read-only
```

I'm new to OpenCV, so it could be user error, but I'm not seeing anything about this online.

Thanks.

**Comment by toddsampson** [comment]
Figured it out... Needed to use `surf.setHessianThreshold(500)`

**Comment by Walid-Ahmed** [comment]
Thanks
How can I  access it to print its value?
