### ISSUE TITLE
Matlab missing many opencv functions

### ISSUE THREAD

**Issue by chenfisher** [Itseez/opencv_contrib#395]
I've successfully built opencv + contrib + the matlab module and it seems I have access to the cv namespace.

I'm trying to use BackgroundSubstractorMOG2 but there's no such class/function.
It seems many other classes are missing.

Any idea how can I use cv.BackgroundSubstractorMOG2 ?

Thanks

**Comment by berak** [comment]
you're right, currently only the dnn module in contrib has matlab bindings.

but they all follow the same pattern, each module has a CMakeLists.txt , containing a line like: 

    ocv_add_module(dnn opencv_core opencv_imgproc WRAP python matlab)

so, try to do the same for the bgsegm module (just add matlab at the end)

**Comment by chenfisher** [comment]
thanks @berak, I'll stick to mexopencv for now.

**Comment by i-akbari** [comment]
I want to use CUDA functions in OpenCV but they don't have Matlab binding. I add some CUDA modules to ".../opencv_contrib-master/modules/matlab/CMakeLists.txt" file.

ocv_add_module(matlab   BINDINGS
                        OPTIONAL opencv_core
                                 opencv_imgproc opencv_ml
                                 opencv_imgcodecs opencv_videoio opencv_highgui
                                 opencv_objdetect opencv_flann opencv_features2d
                                 opencv_photo opencv_video opencv_videostab
                                 opencv_calib opencv_calib3d
                                 opencv_stitching opencv_superres
                                 opencv_xfeatures2d
                                 opencv_hal
                                 **opencv_cudaimgproc opencv_cudawarping
                                 opencv_cudev opencv_cudaarithm opencv_cudabgsegm opencv_
                                 cudafilters opencv_cudacodec
                                 opencv_cudafeatures2d opencv_cudalegacy opencv_cudaobjdetect 
                                 opencv_cudaoptflow opencv_cudastereo**
)

I found modules' names from in the output of cmake command. I just add opencv_ prefix to them, But the bindings wasn't created. How can I make these bindings? For example I want to use cv::cuda::resize in Matlab. Is it possible with Matlab modules?
