### ISSUE TITLE
Segmentation fault when using createCaffeImporter

### ISSUE THREAD

**Issue by khunglongs73** [Itseez/opencv_contrib#396]
Hi,

I follow this example (http://docs.opencv.org/master/d5/de7/tutorial_dnn_googlenet.html#gsc.tab=0) and got Segmentation Fault error. This issue is already reported in issue #383 and fixed in #391 by @rokm. However, after merged the code from #391 I still get the same error. 

This happens even with this simple code

test_dnn.cpp:

```cpp
#include <opencv2/dnn.hpp>
using namespace cv;
using namespace cv::dnn;

int main (int argc, char **argv)
{
       Ptr<Importer> importer = createCaffeImporter("bvlc_googlenet.prototxt", "bvlc_googlenet.caffemodel");
       return 0;
}
```
```bash
g++ test_dnn.cpp -o test -L/usr/local/lib -I/usr/local/include -lopencv_core -lopencv_dnn
```
The output from gdb core dumped:
```bash
Core was generated by `./test_dnn'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9677de290f in cv::dnn::LayerFactory::registerLayer(cv::String const&, cv::Ptr<cv::dnn::Layer> (*)(cv::dnn::LayerParams&)) ()
   from /usr/local/lib/libopencv_dnn.so.3.0
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
```

**Comment by rokm** [comment]
Hey,

can you rebuild OpenCV with debugging symbols enabled (e.g., -DCMAKE_BUILD_TYPE=RelWithDebInfo) to get more detailed backtrace?

**Comment by khunglongs73** [comment]
This is weird, I rebuild everything again and the problem is gone. Thanks again for your fix @rokm.
