### ISSUE TITLE
DNN module on android

### ISSUE THREAD

**Issue by mongoose54** [Itseez/opencv_contrib#399]
I am interested in running OpenCV with DNN module on Android. Is this possible? How can I build opencv_contrib with Android support?

**Comment by mtngld** [comment]
+1

**Comment by mongoose54** [comment]
Some information for anyone who is interested (cc @mtngld ): 

1) As of now the only way this is feasible is through JNI and C++ (http://answers.opencv.org/question/72935/opencv-android-and-deep-learning-module/)

2) You need to build OpenCV with extra modules from here: https://github.com/Itseez/opencv_contrib

3) I am planning to play with Android Studio per instructions here: https://github.com/quanhua92/NDK_OpenCV_AndroidStudio 

If anyone has any ideas/suggestions/tutorials on building an Android app with calls to C++ OpenCV  functions please add here. All this is quite new to me too.

**Comment by mtngld** [comment]
Thanks!

**Comment by mongoose54** [comment]
Unfortunately I am not able to build the Android OpenCV SDK (https://github.com/Itseez/opencv/blob/master/platforms/android/build_sdk.py) using the additional modules found in contributions. I guess the code has to be modified accordingly but I am not an expert. Any help would be much appreciated. I am interested in the DNN

**Comment by alalek** [comment]
You may look on these builds: http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_android They build a part of full Android SDK - one arch only (ARMv7) but with opencv_contrib modules.
There is this script also: https://github.com/Itseez/opencv/blob/master/platforms/scripts/cmake_android_arm.sh

P.S. You need to specify ANDROID_SDK and ANDROID_NDK/NDKROOT paths.

**Comment by mongoose54** [comment]
@alalek Thanks. Modifying the https://github.com/Itseez/opencv/blob/master/platforms/scripts/cmake_android_arm.sh did the tick: 

```
#!/bin/sh
cd `dirname $0`/..

mkdir -p build_android_arm
cd build_android_arm

cmake -DOPENCV_EXTRA_MODULES_PATH=/Users/alex/Downloads/opencv_contrib/modules -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DCMAKE_TOOLCHAIN_FILE=../android/android.toolchain.cmake $@ ../..
```
This modified script built the Android OpenCV in the ``build_android_arm`` directory with the  ``dnn`` module.
Now my question is how do I import this OpenCV to my Android Studio?

**Comment by mongoose54** [comment]
Some more information: 

I modified Android.mk accordingly to point to the ``build_android_arm`` (http://stackoverflow.com/questions/30202842/opencv-for-android-not-opencv-android-sdk) but when I try to include the ``dnn`` header in the native class ``.cpp`` like this: 
``#include "opencv2/dnn.hpp"``
it says there is no such header. So I guess I need to re-import the OpenCV Java module into the project. How do I do that using the ``build_android_arm`` directory?

**Comment by alalek** [comment]
Did you try to run `make install`? (this should create subdirectory in build_android_arm and put distribution files into it).

P.S. Check CMake log about install path line and don't use "sudo", this will break you system.
```
--   Tests and samples:
--     Tests:                       YES
--     Performance tests:           YES
--     C/C++ Examples:              YES
-- 
--   Install path:                  /build-3/precommit_android/build/install
-- 
--   cvconfig.h is in:              /build-3/precommit_android/build
-- -----------------------------------------------------------------
```

**Comment by mongoose54** [comment]
@alalek nope and that seems to be the issue... :+1:

**Comment by xsorifc28** [comment]
Hi,

I have an Android project running with OpenCV 3.1 native JNI & Java. 

I would like to include the opencv_contrib files. Should I be compiling these into a separate .so library? or include them with the OpenCV default libraries? 

In either case, can someone point me to the right direction?

Thank you.

**Comment by alalek** [comment]
Android projects usually refer to libopencv_java*.so. Try to build it with enabled contrib modules

**Comment by xsorifc28** [comment]
@alalek 
How do I enable the contrib modules, via the Android.mk file?

OPENCV_INSTALL_CONTRIB_MODULES:=on ?

I'm not sure how to enable them, also not sure how to specify the directory for the contrib files.

Thanks in advance!

**Comment by alalek** [comment]
You need to build OpenCV  from sources with `OPENCV_EXTRA_MODULES_PATH` CMake parameter.
See here for reference: http://pullrequest.opencv.org/buildbot/builders/master_noOCL-android/builds/188/steps/cmake/logs/stdio

**Comment by mongoose54** [comment]
@xsorifc28 I think this tutorial will help you with building the DNN module: https://github.com/alexkarargyris/Caffe_OpenCV_Android_App

**Comment by xsorifc28** [comment]
@mongoose54 I was trying to compile on Windows, any suggestions for that?

**Comment by nannanmath** [comment]
I use this tutorial https://github.com/alexkarargyris/Caffe_OpenCV_Android_App and opencv with opencv-contrib can be compiled successfully, but I can not find the java folder in opencv/platforms/build_android_arm/install/sdk, there are etc and native folders only.

**Comment by gjongerh** [comment]
This solved my problem

export ANDROID_SDK_ROOT=/Users/gjongerh/Library/Android/sdk
export ANDROID_NDK=/Users/gjongerh/Library/Android/sdk/ndk-bundle
export PATH=$PATH:$ANDROID_NDK
export ANDROID_NATIVE_API_LEVEL=android-19  (Specified Android native API level 'android-8' is not supported by your)
export CMAKE_C_COMPILER=`ndk-which gcc`     (CMake Error at /opt/local/share/cmake-

**Comment by gjongerh** [comment]
export ANDROID_SDK_ROOT=/Users/gjongerh/Library/Android/sdk
export ANDROID_NDK=/Users/gjongerh/Library/Android/sdk/ndk-bundle
export PATH=$PATH:$ANDROID_NDK
export ANDROID_NATIVE_API_LEVEL=android-19  (Specified Android native API level 'android-8' is not supported by your)
export CMAKE_C_COMPILER=`ndk-which gcc`     (CMake Error at /opt/local/share/cmake-3.4/Modules/TestBigEndian.cmake:51)
export CMAKE_CXX_COMPILER=`ndk-which gcc`

**Comment by tzutalin** [comment]
Try this?
http://tzutalin.blogspot.tw/2016/01/installing-opencv-310-and-contrib-lib.html
