### ISSUE TITLE
Minor bug on "caffe_googlenet.cpp" sample application

### ISSUE THREAD

**Issue by mongoose54** [Itseez/opencv_contrib#400]
Just discovered a minor bug at line https://github.com/Itseez/opencv_contrib/blob/master/modules/dnn/samples/caffe_googlenet.cpp#L87

it should be:

```    
String modelTxt = "bvlc_googlenet.prototxt.txt";
``` 

It is missing `.txt`

**Comment by StevenPuttemans** [comment]
Could you provide a PR with the suggested fix? This will help us getting it fixed way faster. Guide on how to do so can be found here: https://github.com/Itseez/opencv/wiki/How_to_contribute

**Comment by berak** [comment]
hmm, the file is named [bvlc_googlenet.prototxt](https://github.com/Itseez/opencv_contrib/blob/master/modules/dnn/samples/bvlc_googlenet.prototxt) , without txt extension.
