### ISSUE TITLE
Custom handling of FaceRecognizer results

### ISSUE THREAD

**Issue by comdiv** [Itseez/opencv_contrib#401]
For now FaceRecognizer allows only one type of prediction result handling - "max confedence". This type of result handling is not all that needed from recognition.

We have many cases where we must to check:
1) Average confidence over trained set (for example we try to decide women/men, child/adult) so we haven't exactly same faces, but average confidence over groups can give us answer
2) Top N "most similar" - in scenario where we have photos with bad quality (from secure cams and so on) and trained base with 1-2 image per person - so it's frequently that "lightly similar" faces are faces of same persons
3) Sharding of training set with following aggregation over shard results - while shard can be not well balanced their confidences can be not directly comparable - so we require use some logic over raw per-shard result

Suggestion:
1. Allow caller side to supply own result handling delegate with addition method of FaceRecognizer
2. It must work same way as usual "predict" but without checking of best result

Implementation:
I have implement it myself in 
https://github.com/comdiv/opencv_contrib/commit/a3ca6d7bddc96530370e882cc842490c4c7aab9d
and it has correspond pull request #402 

It's very simple implementation:
1) std::function used as delegate base class (so it allows to use lambdas and method references clear way)
2) predict_collect method added for FaceRecognizer and all it's descendants - I thought to use existed "predict" name and overload it, but while it's forked code - decide that better use special name
3) all implementations of FaceRecognizer implements this method - it's just copy of existed "predict" - but it send all result to delegate - alternately, while collect sygnature is more generic than exited predict it was able to make predict_collect method main and predict as overload to it, but as in (2) it could be not much friendly in contributed code

Conclusion:
1) Think that predict->(src, collector) notation is very usefull in many scenarios
2) It's simply to implement and use and doesn't require breaking changes to API
3) If there are some suggestions I can fix my code and remake pull request

**Comment by berak** [comment]
there is a related pr [here](https://github.com/Itseez/opencv_contrib/pull/359) , (also related problems)

**Comment by comdiv** [comment]
Related problem can lead to large memory consumption. Think that collector pattern is safer and ease to use in aggregation and map-reduce scenarios.

**Comment by berak** [comment]
in general , do we **want** c++11 dependancy here ? older compilers won't be able to build this module any more.

**Comment by comdiv** [comment]
Heh, haven't check it out. 
Think best solution is:
1) Add overloaded sygnature with (void*)(int,double) instead of std::funciton - template may be?
2) Decorate std::function based declaration and overloads if #ifdef CPP_11_PLUS

So i don't know what to use in #ifdef, can you suggest what to write in #ifdef to target C++ 11 and newer?

**Comment by berak** [comment]
hmm, yes. might work. i'm just unsure, where the CPP_11_PLUS would come from (could not find anything in cvConfig.h or the various cmake settings.

maybe :

<pre>
#ifdef CPP_11_PLUS
  using PredictCollector = std::function<void(int, double)>;
#else 
  typedef void (PredictCollector*)(int, double);
#endif 
</pre>

**Comment by comdiv** [comment]
It's good only if certain C++ 11 compiler guarantees that old client code based on  void (PredictCollector*)(int, double) will compile well and casted to std::function<void(int, double)> automatically.

I'm not sure that such behavior of std::function is a part of must-to-implement standard and will not changed further.

More clear is to supply typedef void (PredictCollectorFunc*)(int, double); by default for all versions and optionally overloaded  using PredictCollector = std::function<void(int, double)>; notation.

But it's still question - how to decide inside of module WHICH version of C++ used and supply valid #ifdef -  i have search google about it and i think it's task to implement in core of cmake files of opencv (have no much compentence in it to supply myself). 

Try add -std=c++11 to CMakeList.txt of face module:
```
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```
But compiler (VS2015) writes:
```
Command line warning D9002: ignoring unknown option '-std=c++11'
```

What i have done invalid?

**Comment by comdiv** [comment]
Have solved it with:
```
#if ((defined(_MSC_VER) && _MSC_VER >= 1700)||(defined(__GNUC__)&& (__GNUC__>4 || (__GNUC__ == 4 && __GNUC_MINOR__>=5 ))))
#define _SUPPORT_FUNCTIONAL 1
#endif
```
in face.hpp

Think that better to have such things in common and add support for more platforms.
Now it's safe - anywhere except VSCPP 17+ or GNU GCC 4.5+ it will not use <functional> and std::function, but just  typedef void (*PredictCollectorFunc)(int, double); otherwise additional overloaded version of predict_collect will be added to API

**Comment by comdiv** [comment]
It cannot build even with c++11 option
```
if(CMAKE_COMPILER_IS_GNUCXX)
    message(STATUS "GCC detected, adding compile flags")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pedantic -Wall -Wextra")
endif(CMAKE_COMPILER_IS_GNUCXX)
```
- it's not working!
if i keep just
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
I got warning in MS VC 64 and still error on Linux that "function" is not type of "std".

It's really crazy (i'm used to deal with .NET and Java 95% of time) ))

**Comment by berak** [comment]
the warnings will go away if you use `#ifdef` instead of `#if`

**Comment by comdiv** [comment]
oops )) in russian it called "soaped eye" 
Have fixed
1) ```#if -> #ifdef```
2) rewrite API ```predict_collect (... void(int, double)) -> predict_collect (... void (int, double, int), int )``` where last parameter is send-back state token  - so it's much friendly for multithread or multisession scenario and for aggregations - especially with C++ < 11 where it's not possible to use std::function and avoid lambda constraints to not have fixed side if used as function-pointer parameter

**Comment by comdiv** [comment]
If this subject is interested i think it's good idea to provide iterator pattern for FaceRecognizer:
```
struct PredictRecord { int label, double dist, int state };
class PredictRecordIterator { PredictRecord  next(); void close(); }
enum PredictRecordIteratorFlags { FR_PRI_LOCK =1, FR_PRI_NO_LOCK =2, FR_PRI_DEFAULT = FR_PRI_LOCK}
class FaceRecognizer {
	private:
		int _iterLocks = 0;
		int _version = 0;
	public:
		PredictRecordIterator open( InputArray src, int state, PredictRecordIteratorFlags flags = PredictRecordIteratorFlags::FR_PRI_DEFAULT ); 
		void incLock();
		void decLock();
		void incVersion();
		void isLocked();
		void isChanged( int baseVersion);
}
train, update, load must check isLocked() - yes - error - no - do it's work and incVersion()
open() - if lock mode - increment lock - if no-lock - provide current version for created iterator
iterator - if lock - if closed or listed to end decLock() - if no-lock - every "next" check if version is still it's base version - if upgraded - error
```

**Comment by comdiv** [comment]
Suggested version complete:
1. No C++11 dependency
2. Python/Java compatible
3. API rewriten to more generic basis with PredictCollector delegate, backward compatible
