### ISSUE TITLE
example_text_end_to_end_recognition can't find tesseract

### ISSUE THREAD

**Issue by ajdroid** [Itseez/opencv_contrib#410]
The `example_text_end_to_end_recognition` example cannot find my tesseract installation. Here is the output:

>IMG_W=800
>IMG_H=600
>TIME_REGION_DETECTION = 528.845
>TIME_GROUPING = 31.0119
>OCRTesseract(33): Tesseract not found.
>TIME_OCR_INITIALIZATION = 0.018044
>OCRTesseract(00): Tesseract not found.
>OCRTesseract(00): Tesseract not found.
>OCRTesseract(00): Tesseract not found.
>OCRTesseract(00): Tesseract not found.
>OCRTesseract(00): Tesseract not found.
>TIME_OCR = 1.31494

This is the result of  `tesseract --version`
>tesseract 3.03
 >leptonica-1.70
  >libgif 4.1.6(?) : libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : webp 0.4.0

Any ideas as to why this happens?  I have installed tesseract after compiling OpenCV, but that is not a problem, is it?

**Comment by berak** [comment]
I have installed tesseract after compiling OpenCV, but that is not a problem, is it? - it is. the text module has to get linked ahgainst tesseract at build time.

re-run cmake, make sure it find tesseract, make, make install.

**Comment by ajdroid** [comment]
That fixed it

**Comment by ajdroid** [comment]
@berak , This worked, but how do I check if tesseract was found after cmake is done generating?

**Comment by ajdroid** [comment]
I was installing on another computer and the same thing happened. I think there is an issue with FindTesseract.cmake
I had to manually set liblept path in this file both times.

**Comment by mshabunin** [comment]
What is your system configuration?

**Comment by ajdroid** [comment]
Both are 64-bit linux machines. Ubuntu 14.04.

**Comment by mshabunin** [comment]
Doesn't cmake find the libraries (check for `-- Tesseract:   YES` in the output)? Where are tesseract and leptonica libraries located?

**Comment by ajdroid** [comment]
No, I had set the paths in FindTesseract.cmake manually both times. Only then did it find the libs. They are in ```/usr/local/lib/```
