### ISSUE TITLE
Compiler error "isVector" is not "cv::InputArray" member

### ISSUE THREAD

**Issue by Poisondox** [Itseez/opencv_contrib#418]
I use python3.4.3 + opencv3.0 and try to build the opencv_contrib modules under windows environment
but compiler tip error  "isVector" is not "cv::InputArray" member . I find source code in sparse_match_interpolators.cpp and try modify the code. I replace "isVector()" with "isMatVector()"
and then compile is succeed,but i'm not sure if I'm right.Can you give me some advice,thanks.

The source code is  under the \opencv_contrib-master\modules\ximgproc\src directory

**Comment by thirus** [comment]
Same issue. Solved by replacing "isVector()" with "isMatVector()", don't if this is right.

**Comment by Poisondox** [comment]
All right,thanks for your help.
