### ISSUE TITLE
readme seems to have an error.

### ISSUE THREAD

**Issue by zhounanzhao** [Itseez/opencv_contrib#472]
press the configure button followed by the generate button (the first time, you will be asked which makefile style to use)
the configure button and the generate button may shoul be be switched.

**Comment by mshabunin** [comment]
The "Generate" button should be pressed at the end, so the instruction is correct:
- press "Configure"
- set parameters
- press "Configure" again
- perss "Generate"

**Comment by zhounanzhao** [comment]
mshabunin thank you very much.
