### ISSUE TITLE
SFM module example error (reconstruct not declared in this scope )

### ISSUE THREAD

**Issue by Wababa** [Itseez/opencv_contrib#476]
Hi,
I followed the steps from the opencv docs to install the dependencies and the Ceres solver for the SFM module and everything seemed to have worked. Afterwards I tried compiling the example code and I get the following error:
structure.cpp:118:77: error: ‘reconstruct’ was not declared in this scope
   reconstruct(points2d, Rs_est, ts_est, K, points3d_estimated, is_projective);

The full code can be found here: http://docs.opencv.org/master/d4/d18/tutorial_sfm_scene_reconstruction.html#gsc.tab=0

Im running Ubuntu 14.04.

I hope someone can help me. Thank you!

**Comment by mshabunin** [comment]
Probably you have not provided enough dependencies for the build. This example is checked on buildbot and the build is fine. How do you build it? Please provide more details.

**Comment by Wababa** [comment]
Sorry for my ignorance, but I'm pretty new at this. Here is what I've done.
Before installing OpenCV I installed the dependencies as shown here: http://docs.opencv.org/master/db/db8/tutorial_sfm_installation.html#gsc.tab=0

To install OpenCV:
1. Download OpenCV
2. Download OpenCV_contrib
3.Go to OpenCV folder and create build folder.
4. execute "cmake -D OPENCV_EXTRA_MODULES_PATH=opencv_contribpath .. " in build folder
4. make -j4
5. sudo make install
Until here everything seems to be OK.

To compile the example code I did:
1. Create a folder where I place the reconstruct.cpp with the example code.
2. Create the following CMakeLists.txt
   cmake_minimum_required(VERSION 2.8) 
   project( Reconstruct )
   find_package( OpenCV REQUIRED)
   include_directories( ${OpenCV_INCLUDE_DIRS} )
   add_executable( Reconstruct structure.cpp )
   target_link_libraries( Reconstruct ${OpenCV_LIBS} )
3. cmake .. 
4. make

And the error pops up. Have I done something wrong? Am I missing something?
I apreciate every help.
Thank you!

**Comment by mshabunin** [comment]
Add `message(STATUS "Found OpenCV version ${OpenCV_VERSION}")` after `find_package` in your CMakeLists.txt

**Comment by mshabunin** [comment]
Also, it could be better to build this example by adding `-DBUILD_EXAMPLES=ON` cmake option before OpenCV build. Then the example will be automatically compiled with all dependencies and put into `<build-dir>/bin` folder (`build/bin/example_sfm_scene_reconstruction`).

**Comment by Wababa** [comment]
Seems that OpenCV is found, I got the following: -- Found OpenCV version 3.0.0
If I build the example like the way you say, won't I get the same error in case I write my own code using the module?

**Comment by Wababa** [comment]
With the -DBUILD_EXAMPLES=ON it does work. :/

**Comment by edgarriba** [comment]
@Wababa could you check that after installing you got the sfm module headers copied into your filesystem? This smacks to me there's an issue in the installation part.

**Comment by manishaluthra** [comment]
@edgarriba @mshabunin I have the same problem, but mine did not go away with -DBUILD_EXAMPLES=ON  flag. Indeed the sfm module headers are there in my filesystem, so i do not get errors including the headers and the namespace cv::sfm. But only on reconstruct method :| thats strange! I can call other methods of sfm including homogeneousToEuclidean but not reconstruct. Though i get the executable of the example (sfm_scene_recontruction) in bin directory successfully, as the build was successful.

**Comment by Debize** [comment]
I have exactly the same issue as @Wababa, *cv::sfm::reconstruct()* is not recognized.
The strange thing is that others functions of the *cv::sfm* namespace are well recognised (*cv::sfm::projectionFromKRt()* for exemple).

I have:
- /usr/locate/include/opencv2/sfm/ 
 - conditioning.hpp  
 - fundamental.hpp  
 - numeric.hpp 
 - projection.hpp 
 - reconstruct.hpp  
 - robust.hpp   
 - simple_pipeline.hpp  
 - triangulation.hpp

I don't really know what to do.
Thank you for your help!

**Comment by Wababa** [comment]
@manishaluthra Actually It didn't work with the DBUILD_EXAMPLES=ON, sorry for expressing myself wrong. I meant that the compiled example worked. @edgarriba I have the same headers as @Debize.

**Comment by edgarriba** [comment]
hey wait, do you guys have Ceres installed? For reconstruction and build samples is needed.

There's a note explaining that plus a tutorial about Ceres installation:
http://docs.opencv.org/master/d7/de2/group__simple__pipeline.html#gsc.tab=0
http://docs.opencv.org/master/db/db8/tutorial_sfm_installation.html#gsc.tab=0

Check as well that in case you don't have Ceres then examples are not built:
https://github.com/Itseez/opencv_contrib/blob/master/modules/sfm/CMakeLists.txt#L130

**Comment by manishaluthra** [comment]
yes i have the same issue too @Debize, i have the sfm module headers as well in */usr/local/include/opencv2/sfm* including **reconstruct.hpp**. *example_sfm_scene_reconstruction* works for me too, there indeed are some differences in compilation of example. Just when I write my own example, *cv::sfm::reconstruct()* do not get recognized. @edgarriba i did install Ceres, here are the libraries installed: */usr/local/include/ceres*.

**Comment by leetenthu** [comment]
Hello all, I have the same issue. Any suggestion would be great!

**Comment by BorgesJVT** [comment]
Hey guys! I had these same problems. I knew that i had installed ceres and it was visible, so i just opened the files 'reconstruct.hpp' and 'sfm.hpp' and commented the directive 'if CERES NOT FOUND'.
After that, i could compile and run the sfm samples.

PS: Virtual machine may cause  some problems.

**Comment by raderic** [comment]
@BorgesJVT 
I have done you said but now I get a linker error:

>  undefined reference to `cv::sfm::reconstruct

I've installed CERES and I don't know what is a problem.
Could you help me? For example, show me your CMakeList. 
Thanks .

**Comment by jiaojingguoguo** [comment]
@BorgesJVT very good!   你说的对！

**Comment by ntthuy11** [comment]
@BorgesJVT I had the same issue. Thanks a lot for that. I commented 'if CERES NOT FOUND' and the code could be built, but no Visualization view was showed after executing this command:

./example_sfm_scene_reconstruction image_paths_file.txt 350 240 360

I wonder if you had the point cloud as in here: https://github.com/Itseez/opencv_contrib/tree/master/modules/sfm
I guess the issue was from Ceres Solver, but I don't know how to fix it.

I really appreciate your help.

**Comment by ntthuy11** [comment]
This command:

./example_sfm_trajectory_reconstruction tracks_file.txt 1914 640 360

worked well for me (display as same as in https://github.com/Itseez/opencv_contrib/tree/master/modules/sfm). It means that I had no problem with building OpenCV 3.1 + opencv_contrib (with VTK, opencv_viz). Ceres did not show anything wrong.

**Comment by BorgesJVT** [comment]
Hi @ntthuy11 I have the same configuration (opencv + ceres) in two virtual machines. In both machines i can compile and execute all sample files, but one of the machines i have the same issue (i can't visualize too). I suppose that it could be some graphical issue, perhaps because of virtual machine or visual graphics limitation. Try use another machine configuration!

**Comment by ntthuy11** [comment]
Hi @BorgesJVT. Thank you very much. I tried to clean everything and install again but I still had the same problem with visualization. But it is fine, as long as the recontruct() function works.

**Comment by alibatiste** [comment]
Hello,
I have the same problem with reconstruct "not found". It's like it can't find Ceres. The example has compile correctly. But i can't find the source of example. Do i need to add option to build with Ceres?
I'm a little lost with this library...

**Comment by miguelriemoliveira** [comment]
Hello,

I had the same problem: I can run the example from opencv, but cannot compile and link my own code. Compiler says reconstruct is undefined. Following the answer from @BorgesJVT  I propose an alternative procedure: 

I added in my code

#define CERES_FOUND true

An it now compiles. In my opinion, its better than changing the source code from opencv_contrib. 

Of course this assumes that you do have CERES installed (I think if you don't a linking error should appear).

I have also have the problem of not seeing anything in the visualizer ...

**Comment by BorgesJVT** [comment]
I agree with @miguelriemoliveira. It's better than change the source code.

**Comment by gunshi** [comment]
I just wanted to add, I am experiencing the same error, and I checked that CERES_FOUND has been set to 0 in files like:
build/modules/sfm/CMakeFiles/opencv_test_sfm.dir, build/modules/sfm/CMakeFiles/opencv_sfm.dir etc
However, the following line exists:

> //The directory containing a CMake configuration file for Ceres.
> Ceres_DIR:PATH=/usr/local/share/Ceres


in cmakecache.txt.

**Comment by gunshi** [comment]
And upon changing the find_package(CERES QUIET) to find_package(CERES REQUIRED)
i get the error (in the output of cmake)
Found package configuration file:

    /usr/local/share/Ceres/CeresConfig.cmake

  but it set Ceres_FOUND to FALSE so package "Ceres" is considered to be NOT
  FOUND.


What can I do now?
I did a successful brew install of ceres beforehand, as well as the dependencies.

**Comment by miguelriemoliveira** [comment]
@gunshi, why don't you do as I suggested above?

**Comment by gunshi** [comment]
Hi, I was able to resoolve the error, which was due to a version mismatch between eigen and ceres, as described in the config cmake file for ceres, and that was quietly setting both the ceres_found flags to false, despite ceres being installed.

**Comment by miguelriemoliveira** [comment]
Hi @gunshi could you explain how you solved it?

**Comment by gunshi** [comment]
I changed find_package(CERES QUIET) to find_package(CERES REQUIRED), and thus got an error during cmake, which gave a message about eigen version being 3.2.8 and the requested eigen version for ceres being 3.2.7 (as listed in the cmake config file for ceres under /usr/local/share/Ceres).
Ceres reuqests the exact eigen version and not just any version greater than the requested one.
So I downgraded from eigen 3.2.8 to 3.2.7, and then the problem was resolved.

**Comment by botverse** [comment]
Hi, I was having the same problems for compiling and the trick was to use eigen 3.2.7 as mentioned by @gunshi. I also needed the `#define CERES_FOUND true` directive at the top of the example.

To see the visualisation, I added `waitKey(0);` just below `window.spin()`.

`waitKey` is in the `"opencv/highgui.hpp"` header.

**Comment by miguelriemoliveira** [comment]
Hi @botverse if you are using the "#define CERES_FOUND true directive at the top of the example" I do not think you need to bother about downgrading Eigen.

Thanks for the waitkey(0) tip, I will try it.

**Comment by gunshi** [comment]
waitkey(0) didn't work for me, unfortunately.

**Comment by soheilard** [comment]
I could also run sfm sample but I have problem with visualizing! actually no visualization!! I tried waitkey() as well but it doesn work...help please..

**Comment by hilman-dayo** [comment]
Hai guys, I am trying to compile the camera motion estimation code sample and I got this error. I already include the directive `#define CERES_FOUND true`

    /tmp/ccHDBnbF.o: In function `main':
    cam_motion.cpp:(.text+0x999): undefined reference to `cv::sfm::reconstruct(cv::_InputArray const&,  cv::_OutputArray const&, cv::_OutputArray const&, cv::_InputOutputArray const&, cv::_OutputArray const&, bool)'
    cam_motion.cpp:(.text+0xb5a): undefined reference to `cv::viz::Viz3d::Viz3d(cv::String const&)'
    cam_motion.cpp:(.text+0xba7): undefined reference to  `cv::viz::Viz3d::setBackgroundColor(cv::viz::Color const&, cv::viz::Color const&)'
cam_motion.cpp:(.text+0xbc0): undefined reference to `cv::viz::Viz3d::registerKeyboardCallback(void     (*)(cv::viz::KeyboardEvent const&, void*), void*)'
    cam_motion.cpp:(.text+0xe2c): undefined reference to `cv::viz::Viz3d::wasStopped() const'
    cam_motion.cpp:(.text+0xeaf): undefined reference to `cv::Mat::eye(int, int, int)'
    cam_motion.cpp:(.text+0xfd4): undefined reference to `cv::viz::WCube::WCube(cv::Point3_<double>     const&, cv::Point3_<double> const&, bool, cv::viz::Color const&)'
    cam_motion.cpp:(.text+0x1001): undefined reference to `cv::viz::Widget::setRenderingProperty(int, double)'
    cam_motion.cpp:(.text+0x1085): undefined reference to `cv::viz::Viz3d::showWidget(cv::String const&, cv::viz::Widget const&, cv::Affine3<double> const&)'
    cam_motion.cpp:(.text+0x11cf): undefined reference to  `cv::viz::WCameraPosition::WCameraPosition(double)'
    cam_motion.cpp:(.text+0x1217): undefined reference to `cv::viz::WCameraPosition::WCameraPosition(cv::Matx<double, 3, 3> const&, double, cv::viz::Color const&)'
    cam_motion.cpp:(.text+0x123b): undefined reference to `cv::viz::Viz3d::setViewerPose(cv::Affine3<double> const&)'
    cam_motion.cpp:(.text+0x12a4): undefined reference to `cv::viz::WTrajectory::WTrajectory(cv::_InputArray const&, int, double, cv::viz::Color const&)'
    cam_motion.cpp:(.text+0x12dc): undefined reference to `cv::viz::Viz3d::showWidget(cv::String const&, cv::viz::Widget const&, cv::Affine3<double> const&)'
    cam_motion.cpp:(.text+0x1341): undefined reference to `cv::viz::Viz3d::showWidget(cv::String const&, cv::viz::Widget const&, cv::Affine3<double> const&)'
    cam_motion.cpp:(.text+0x1388): undefined reference to `cv::viz::Viz3d::showWidget(cv::String const&, cv::viz::Widget const&, cv::Affine3<double> const&)'
    cam_motion.cpp:(.text+0x13ee): undefined reference to `cv::viz::Viz3d::spinOnce(int, bool)'
    cam_motion.cpp:(.text+0x13fd): undefined reference to `cv::viz::Viz3d::removeAllWidgets()'
    cam_motion.cpp:(.text+0x1452): undefined reference to `cv::viz::Viz3d::~Viz3d()'
    cam_motion.cpp:(.text+0x1554): undefined reference to `cv::viz::Viz3d::~Viz3d()'
    cam_motion.cpp:(.text+0x16bb): undefined reference to `cv::viz::Viz3d::~Viz3d()'
    /tmp/ccHDBnbF.o: In function `std::ostream& cv::operator<< <double, 3, 3>(std::ostream&, cv::Matx<double, 3, 3> const&)':
    cam_motion.cpp:(.text+0x1760): undefined reference to `cv::Formatter::get(int)'
    /tmp/ccHDBnbF.o: In function `cv::String::String(char const*)':
    cam_motion.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x4d): undefined reference to `cv::String::allocate(unsigned long)'
/tmp/ccHDBnbF.o: In function `cv::String::~String()':
    cam_motion.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to `cv::String::deallocate()'
    /tmp/ccHDBnbF.o: In function `cv::Mat::Mat(cv::Mat const&)':
    cam_motion.cpp:(.text._ZN2cv3MatC2ERKS0_[_ZN2cv3MatC5ERKS0_]+0x17d): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
    /tmp/ccHDBnbF.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
    cam_motion.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x130): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
    cam_motion.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x237): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
    /tmp/ccHDBnbF.o: In function `cv::Mat::~Mat()':
    cam_motion.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x39): undefined reference to `cv::fastFree(void*)'
    /tmp/ccHDBnbF.o: In function `cv::Mat::operator=(cv::Mat const&)':
    cam_motion.cpp:(.text._ZN2cv3MataSERKS0_[_ZN2cv3MataSERKS0_]+0x115): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
    /tmp/ccHDBnbF.o: In function `cv::Mat::create(int, int, int)':
    cam_motion.cpp:(.text._ZN2cv3Mat6createEiii[_ZN2cv3Mat6createEiii]+0x9d): undefined reference to `cv::Mat::create(int, int const*, int)'
    /tmp/ccHDBnbF.o: In function `cv::Mat::release()':
    cam_motion.cpp:(.text._ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x4b): undefined reference to `cv::Mat::deallocate()'
    /tmp/ccHDBnbF.o: In function `cv::Mat::operator()(cv::Rect_<int> const&) const':
    cam_motion.cpp:(.text._ZNK2cv3MatclERKNS_5Rect_IiEE[_ZNK2cv3MatclERKNS_5Rect_IiEE]+0x27): undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
    /tmp/ccHDBnbF.o: In function `cv::String::String(std::__cxx11::basic_string<char,     std::char_traits<char>, std::allocator<char> > const&)':
    cam_motion.cpp:(.text._ZN2cv6StringC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN2cv6StringC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x69): undefined reference to `cv::String::allocate(unsigned long)'
    /tmp/ccHDBnbF.o: In function `cv::viz::Widget3D::~Widget3D()':
    cam_motion.cpp:(.text._ZN2cv3viz8Widget3DD2Ev[_ZN2cv3viz8Widget3DD5Ev]+0x14): undefined reference to `cv::viz::Widget::~Widget()'
    /tmp/ccHDBnbF.o: In function `_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi3EEEv':
    cam_motion.cpp:(.text._ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi3EEEv[_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi3EEEv]+0xd9): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
    cam_motion.cpp:(.text._ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi3EEEv[_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi3EEEv]+0x1d0): undefined reference to `cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const'
    /tmp/ccHDBnbF.o: In function `_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIdLi3EEEv':
    cam_motion.cpp:(.text._ZNK2cv3MatcvNS_3VecIT_XT0_EEEIdLi3EEEv[_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIdLi3EEEv]+0xd9): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
    cam_motion.cpp:(.text._ZNK2cv3MatcvNS_3VecIT_XT0_EEEIdLi3EEEv[_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIdLi3EEEv]+0x1d0): undefined reference to `cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const'
    /tmp/ccHDBnbF.o: In function `cv::Affine3<double>::Affine3(cv::Mat const&, cv::Vec<double, 3> const&)':
    cam_motion.cpp:(.text._ZN2cv7Affine3IdEC2ERKNS_3MatERKNS_3VecIdLi3EEE[_ZN2cv7Affine3IdEC5ERKNS_3MatERKNS_3VecIdLi3EEE]+0x8c): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
    cam_motion.cpp:(.text._ZN2cv7Affine3IdEC2ERKNS_3MatERKNS_3VecIdLi3EEE[_ZN2cv7Affine3IdEC5ERKNS_3MatERKNS_3VecIdLi3EEE]+0xeb): undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
    /tmp/ccHDBnbF.o: In function `cv::Mat::Mat<double, 3, 3>(cv::Matx<double, 3, 3> const&, bool)':
    cam_motion.cpp:(.text._ZN2cv3MatC2IdLi3ELi3EEERKNS_4MatxIT_XT0_EXT1_EEEb[_ZN2cv3MatC5IdLi3ELi3EEERKNS_4MatxIT_XT0_EXT1_EEEb]+0x227): undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
    /tmp/ccHDBnbF.o: In function `cv::Affine3<double>::rotation(cv::Mat const&)':
    cam_motion.cpp:(.text._ZN2cv7Affine3IdE8rotationERKNS_3MatE[_ZN2cv7Affine3IdE8rotationERKNS_3MatE]+0x76): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
    cam_motion.cpp:(.text._ZN2cv7Affine3IdE8rotationERKNS_3MatE[_ZN2cv7Affine3IdE8rotationERKNS_3MatE]+0xde): undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
    cam_motion.cpp:(.text._ZN2cv7Affine3IdE8rotationERKNS_3MatE[_ZN2cv7Affine3IdE8rotationERKNS_3MatE]+0x191): undefined reference to `cv::Mat::reshape(int, int) const'
    cam_motion.cpp:(.text._ZN2cv7Affine3IdE8rotationERKNS_3MatE[_ZN2cv7Affine3IdE8rotationERKNS_3MatE]+0x1a7): undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
    cam_motion.cpp:(.text._ZN2cv7Affine3IdE8rotationERKNS_3MatE[_ZN2cv7Affine3IdE8rotationERKNS_3MatE]+0x215): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
    collect2: error: ld returned 1 exit status

**Comment by snakehaihai** [comment]
I would assume you use cmake and let it autoconfig. Problem is that if you have multiple version of opencv eg one at /opt/ros/indigoXXXXXXXXXX  another is at /usr local  it will automatically lock in ros one. 

To me. I solve the problem by link manually, there are 6 tab in the opencv group that you need to fill in
/usr/local/share/OpenCV/3rdparty/lib
/usr/local/share/OpenCV/3rdparty/lib
/usr/local/share/OpenCV
/usr/local/share/OpenCV
/usr/local/lib
/usr/local/lib

if you use auto config, only first 4 will be filled in leave the other 2 open. which also wont work. 


@Wababa

**Comment by lvzhen3931** [comment]
For visualization, I tried to zoom out a little bit, the point cloud can be seen then. With or without waitKey(0).

**Comment by bcWorkAccount** [comment]
Hi, I was having the same problems for compiling,I do 
    #define CERES_FOUND true        at the top of the example
    find_package(OpenCV 3.3.1 REQUIRED)     at cmake file
it works for me.

**Comment by jinfagang** [comment]
I think uncomment the sfm.hpp and reconstruct #if CERES_FOUND is not a good idea, I got this error:

```
Users/jintian/opencv/opencv_contrib/modules/sfm/src/reconstruct.cpp:131:9: error: no matching
      function for call to 'reconstruct'
        reconstruct(points2d, Rs, Ts, Ka, points3d, is_projective);
```

Anyone have suggestions?

**Comment by jinfagang** [comment]
Ok, things not simple as I know, I succeed build the sfm module with uncomment both CERES and DOXYGEN, I can load reconstruct now, but when I build my program, it says:

```
/usr/local/include/opencv2/core/traits.hpp:366:31: error: no member named 'type' in
      'cv::DataType<std::__1::basic_string<char> >'
{ enum { value = DataType<T>::type }; };
                 ~~~~~~~~~~~~~^
/usr/local/include/opencv2/core/mat.inl.hpp:85:42: note: in instantiation of template class
      'cv::traits::Type<std::__1::basic_string<char> >' requested here
{ init(FIXED_TYPE + STD_VECTOR + traits::Type<_Tp>::value + ACCESS_READ, &vec); }
                                         ^
/Volumes/xs/CodeSpace/CppSpace/reconstructor/main.cpp:81:30: note: in instantiation of function
      template specialization 'cv::_InputArray::_InputArray<std::__1::basic_string<char> >'
      requested here
        cv::sfm::reconstruct(sequence_files, Rs_est, ts_est, K, points3d_estimated, is_p...
                             ^
In file included from /Volumes/xs/CodeSpace/CppSpace/reconstructor/main.cpp:28:
In file included from /usr/local/include/opencv/cv.hpp:50:
In file included from /usr/local/include/opencv/cv.h:63:
In file included from /usr/local/include/opencv2/core/core_c.h:48:
In file included from /usr/local/include/opencv2/core/types_c.h:101:
In file included from /usr/local/include/opencv2/core.hpp:59:
In file included from /usr/local/include/opencv2/core/mat.hpp:3642:
/usr/local/include/opencv2/core/mat.inl.hpp:85:51: error: incomplete definition of type
      'cv::traits::Type<std::__1::basic_string<char> >'
{ init(FIXED_TYPE + STD_VECTOR + traits::Type<_Tp>::value + ACCESS_READ, &vec); }
                                 ~~~~~~~~~~~~~~~~~^~
/Volumes/xs/CodeSpace/CppSpace/reconstructor/main.cpp:81:30: note: in instantiation of function
      template specialization 'cv::_InputArray::_InputArray<std::__1::basic_string<char> >'
      requested here
        cv::sfm::reconstruct(sequence_files, Rs_est, ts_est, K, points3d_estimated, is_p...
                             ^
1 warning and 2 errors generated.
```

Compeletely have now idea what is going on??

**Comment by alalek** [comment]
> /Volumes/xs/CodeSpace/CppSpace/reconstructor/main.cpp

This code tries to work with `cv::Mat` with `std::string` elements. This is not supported and forbidden.

**Comment by jinfagang** [comment]
@alalek I am just token the tutorial code from https://docs.opencv.org/3.1.0/d4/d18/tutorial_sfm_scene_reconstruction.html , and I am just using the original usage of sfm::recontrcut:

```
vector<Mat> Rs_est, ts_est, points3d_estimated;
  reconstruct(images_paths, Rs_est, ts_est, K, points3d_estimated, is_projective);
```
I think there is nothing to do with your addressed issue.

**Comment by alalek** [comment]
@jinfagang You should open a new issue about invalid types in sfm samples. It is not related to original issue.

**Comment by billy-antoine** [comment]
Hi,
@jinfagang did you open a new issue or find the answer to your problem ..? Because I am in the exact same situation.

**Comment by samhartlebury** [comment]
I know this is an old post now, but for anybody else who is trying to build the extra opencv modules from source (on windows); I found that if you use cmake to build and install Ceres-solver from source, it doesnt install correctly. You need to make sure you have gflags and glog build from Visual Studio, then build Ceres in debug mode, the release mode, in Visual Studio. THEN build the "INSTALL" project in release and it should install correctly. 

Make sure to close cmake and re-open then when you configure opencv it "should" pick up the new install location
