### ISSUE TITLE
[ximgproc] SLIC superpixels: contour mask contains {-1,1} instead of {-1,0}

### ISSUE THREAD

**Issue by ehku** [Itseez/opencv_contrib#481]
The mask returned by getLabelContourMask() contains -1 at the segmentation contours and 1 elsewhere, which is not a valid mask. A valid mask should contains 'a' (where a != 0) at the contours and 0 elsewhere (e.g. in the case of SEEDS: a = 255).

**Comment by cbalint13** [comment]
Thanks a lot @ehku !

PR https://github.com/Itseez/opencv_contrib/pull/483 is onlgoing to address the issue. I made SLIC & LSC masks just like SEEDS one. Also matrix should be CV_8UC1 type.

**Comment by ehku** [comment]
Thanks, @cbalint13 !!

**Comment by cbalint13** [comment]
@ehku ,

Revisitied the patch. Matrix should be 8UC1, so i corrected ```seeds.cpp``` too. See here the reason:
* https://github.com/Itseez/opencv/blob/master/modules/imgproc/src/contours.cpp#L197
