### ISSUE TITLE
Opencv3.0.0‘s bug of imread function

### ISSUE THREAD

**Issue by DengPingFan** [Itseez/opencv_contrib#488]
My platform is windows 64bit,visual stdio 2013,i am using the opencv2.4.11 and opencv3.0.0

to test the imread function.And I have find that use the opencv3.0.0 to read *.jpg

image file will produce the different result with use the opencv2.4.11.I guess maybe the opencv3.0.0

imread() function's decompression has wrong.

https://cloud.githubusercontent.com/assets/16174941/11987817/e7b0a696-aa20-11e5-85f8-8f72c3708b72.png

**Comment by DengPingFan** [comment]
#include "stdafx.h"
#include <opencv/cv.h>
#include <opencv2/opencv.hpp>

#ifdef _DEBUG
#define lnkLIB(name) name "d"
#else
#define lnkLIB(name) name
#endif

#define CV_VERSION_ID CVAUX_STR(CV_MAJOR_VERSION) CVAUX_STR(CV_MINOR_VERSION) CVAUX_STR(CV_SUBMINOR_VERSION)
#define cvLIB(name) lnkLIB("opencv_" name CV_VERSION_ID)
#pragma comment( lib, cvLIB("core"))
#pragma comment( lib, cvLIB("imgproc"))
#pragma comment( lib, cvLIB("highgui"))


#if CV_MAJOR_VERSION == 3
#pragma comment(lib,  cvLIB("imgcodecs")) //the opencv3.0 need it
#endif

#if CV_MAJOR_VERSION == 2
#pragma comment(lib, cvLIB("contrib"))
#endif


using namespace cv;
using namespace std;

void read_save(string imgPath)
{
    Mat img;
    img = imread(imgPath);

    string savePath = "";//what you want to save path
    imwrite(savePath, img);//save the image to *.png format
}

int _tmain(int argc, _TCHAR* argv[])
{

    ////////////first step./////////////////////
    string path_openCV2411;
    read_save(path_openCV2411);//use the opencv2.4.11 to read and save the image.

    ////////////second step./////////////////////
    //comments the first step code and then use the opencv3.0.0 to read and save this image;
    //string path_openCV300;
    //read_save(path_openCV300);//use the opencv3.0.0 to read and save the image.

    Mat img_openCV2411, img_openCV300;
    Mat difMask;

    img_openCV2411 = imread("str_opencv2411.jpg");//use opencv 2.4.11 read the *.jpg image
    img_openCV300 = imread("str_opencv300.jpg");//use opencv3.0.0 read the *.jpg image

    compare(img_openCV2411, img_openCV300, difMask, CMP_NE);
    imshow("difference", difMask);

    return 0;
}

**Comment by DengPingFan** [comment]
1.use opencv2.4.11 to read it and then save it with .png format(eg. save as img2411.png)
2.use opencv3.0.0 to read it and then save it with .png format (eg. save as img300.png)
3.read this two *.png image file
4.compare it with compare() function you will find there are too difference. 
![Uploading 77.jpg…]()

**Comment by Dikay900** [comment]
please do not crosspost these issues across multiple repositories. Stay at the opencv main repository for this issue and close this please.
