### ISSUE TITLE
typo bug in tracking module

### ISSUE THREAD

**Issue by 7oud** [Itseez/opencv_contrib#492]
tracking/src/roiSelector.cpp
line 111
    // end selection process on SPACE (32) BACKSPACE (27) or ENTER (13)
    while(!(key==32 || key==27 || key==13)){
line 162
    // while key is not Backspace
    while(key!=27){

key == 27 means "ESC" key, not "BACKSPACE“

**Comment by sturkmen72** [comment]
this issue can be closed down
