### ISSUE TITLE
dnn::Net::forward() error with custom trained caffe Model

### ISSUE THREAD

**Issue by djebm2** [Itseez/opencv_contrib#517]
I encounter the following error when doing forward propagation using custom trained caffe model.
My model has been trained with DIGITS 2 using GoogleNet and latest version of caffe framework. 

    OpenCV Error: Assertion failed (blobs[0].num() == outCn && blobs[0].channels() == inpCn / group) in allocate, file /opencv_contrib/modules/dnn/src/layers/convolution_layer.cpp, line 87 
    terminate called after throwing an instance of 'cv::Exception'
      what():  /opencv_contrib/modules/dnn/src/layers/convolution_layer.cpp:87: error: (-215) blobs[0].num() == outCn && blobs[0].channels() == inpCn / group in function allocate

**Comment by rmekdma** [comment]
I had the same problem. I solved it by resizing image to size of input data dimension specified in prototxt.

**Comment by djebm2** [comment]
Thanks it worked. One more question, is the resulted class index equal to the line number inside the class name txt file ?

**Comment by rmekdma** [comment]
This is the output from `caffe_googlenet.cpp`.

```
Net Outputs(1):
prob
Best class: #812 'space shuttle'
Probability: 99.9813%
```

It shows the most probable class. I don't see class index here. If you refer to the variable `classId` as resulted class index, it seems to be the line number-1 of `synset_words.txt`.
