### ISSUE TITLE
No such file intrin.hpp building xphoto

### ISSUE THREAD

**Issue by daviddoria** [Itseez/opencv_contrib#543]
I got this compiler error:

/home/doriad/src/opencv_contrib/modules/xphoto/src/grayworld_white_balance.cpp:43:39: fatal error: opencv2/core/hal/intrin.hpp: No such file or directory
 #include "opencv2/core/hal/intrin.hpp"

I am building OpenCV 3.0.0

**Comment by daviddoria** [comment]
Ah, I see that the contrib has release tags that correspond to OpenCV. I built OpenCV 3.0.0 against contrib 3.0.0 and all is well. Sorry for the noise.

**Comment by SunnerLi** [comment]
I add the supplement that I have encounter the same problem.
Open the terminal and type as following:
```
sunner@sunner-PC:~$ cd OpenCV/opencv_contrib/
sunner@sunner-PC:~/OpenCV/opencv_contrib$ git checkout 3.0.0
sunner@sunner-PC:~/OpenCV/opencv_contrib$ cd ~/OpenCV/opencv/build/
sunner@sunner-PC:~/OpenCV/opencv/build$ sudo make -j2
```
And it would work.
