### ISSUE TITLE
opencv_ffmpeg problem while compile cmake

### ISSUE THREAD

**Issue by adamib** [Itseez/opencv_contrib#544]
Hi, 

 I've downloaded the latest for both (opencv 3.1 and opencv_contrib) and when I try to compile it in cmake (new version of opencv) it says "Failed to download opencv_ffmpeg.dll. Status=7;"Couldn't connect to server" is there any ideas? thx

**Comment by mshabunin** [comment]
Please, take a look at https://github.com/Itseez/opencv/issues/5546
