### ISSUE TITLE
Cannot build hdf modules on windows

### ISSUE THREAD

**Issue by stereomatchingkiss** [Itseez/opencv_contrib#546]
OS : Win8 64bits
Compiler : vc2013 64bits

Install hdf5 1.8.16 from [(Windows (64-bit)   [1]   Compilers:   CMake VS 2013 C, C++, IVF 15 )](https://www.hdfgroup.org/HDF5/release/obtain5.html)

The first issues is the cmake will complain it can not find the HDF5_LIBRARIES

Second issues is visual c++ expected constant expression

   ```
 // fetch rank
    int n_dims = H5Sget_simple_extent_ndims( fspace );

    // dims storage
    hsize_t dims[n_dims];
```

I guess the problem is n_dims cannot determine at compile time, maybe cv::AutoBuffer could solve this problem?
`
cv::AutoBuffer<hsize_t, 64>`

**Comment by cbalint13** [comment]
@stereomatchingkiss ,

* I'll address today a patch for this issue, i am aware of this. It's already done just need to PR.
* At the moment of intial PR the hdf library was missing on msvc buildbot so there where no feedback.


I'll notice you here when done.

**Comment by cbalint13** [comment]
@stereomatchingkiss ,

- An alpha patch: http://openrisc.rdsor.ro/hdf5-msvc.cpp.diff
- Need to check it in extensive ways and then pass with PR (today).

**Comment by stereomatchingkiss** [comment]
So fast, thanks for the patch. I upload the fix too, I use cv::AutoBuffer to fix the issues rather than raw array and new the memory on heap. It works. but I do not know how to deal with cmake issues yet

[fix](https://github.com/stereomatchingkiss/opencv_contrib/commit/afc41621ef6b14b214a9b96c513e51263987cc23)

**Comment by cbalint13** [comment]
@stereomatchingkiss , as original author:

* With respect, for HDF _low_ level back-end I believe _no_ C+++ (triple plus) style is opportune !
* Allow me a proper msvc fix (just for MSVC), keeping the HDF philosophy, of c-ish style as backend.
* As remainder you can create cv::Mat N-d matrix just passing same simple array int[] to ::Mat.

Lets keep it simple, RTM about cv::Mat.

**Comment by stereomatchingkiss** [comment]
Since you are the author and prefer c-ish style, I respect your decisions :). About the patch, I cannot find delete being called, is it a mistake or some sort of trick?

If you do not like c++ style but prefer low level solution because you are worry about performance, the [paper of bjarne](http://www.stroustrup.com/improving_garcia_stroustrup_2015.pdf) may ease your mind. 

Most of the c++ facilities are simple and intuitive for me, they never looks more complicated than c-ish style solution. Besides, cv::AutoBuffer has the advantages as following

1 : It would allocate memory on stack but not heap(this offer better chance of optimize) if the size of the stack big enough(specify by second parameter).
2 : Even it allocate memory on heap, it will release them after out of life scope(resource always released, no manually memory management)
3 : It support raw array like semantic

**Comment by cbalint13** [comment]
@stereomatchingkiss ,


Well you are right about the differences. Appologies for the little paranoia. Some of my argues that leaded to actual state:

* At design time I had a chance to choose between HDF's C++ and C api. I choosed C one. I believed its more flexible and much better exposed and fitted well with sort of "backend" design of module.  I was thinking to cover and reach out to their multi-thread support too (its still in early stages in their very upstream).

* I was asked at PR time to expose ```std::vector dims``` instead of ```dims[]```. I made booth of them available, thinking that for cv::Mat creation time booth are available too, at least the simple ```dims[]``` is available and easy to use.

* In some circumstances creating / destroying i.e. >10000x times std::vectors makes things slower (e.g. reading/writing to hdf5 object in batch/chunked mode) for very large datasets (muti-giga in size).

I wish to promote hdf5 into main opencv, for this i added a lot of samples in the documentation to show the flexibility. But many things are to be done the most outstanding are perf/test cases. I believe HDF is at par with matlab MAT or even better, it would be pitty to not promote this module.

**Comment by stereomatchingkiss** [comment]
I know c api of hdf5 are flexible than its c++ wrapper, it is perfectly fine to prefer c api if you want better power. 

I am curious about under what circumstance vectors makes things slower, the scene I could think of are

1 : You compare it with stack(ex : int dims[10] vs vector<int> dims(10)), in this case vector will be slower
2 : You compare it with un-initialize raw array, vector will called the default constructor of the elements(ex : int *a = new int[10] vs std::vector<int> a(10))

If it is case 1, cv::AutoBuffer<int, 64> maybe could solve the problem, it would allocate the memory on stack it the buffer is big enough(specify by second argument, in this case, it is 64 int), else it would allocate on heap. The other advantages of AutoBuffer is it follow the semantic of array + do not need you to handle the resource manually. However, performance will need to measure again

If it is case 2, well, maybe raw pointer is the best choice(if you do not want to design a resource management class to handle your array), since opencv still using c++98, we have no zero cost unique_ptr to use.

However, no matter it is c++ or c-ish style, new must pair with delete in most of the cases, else the memory will leak.But I never saw you call delete on your patch.

I always use RAII to handle resource, RAII make things much more easier to handle, but you are the author, the choice is up to you.

**Comment by gansm255** [comment]
Hi,
I could not build hdf. i use opencv_4.1.0 & 4.3.0 along with the respective contrib pack.
I am cross compiling for arm. i am struck with this package for the last week. 
Please guide if i need to declare some macros in some files. 
I already copied HDF5 to contrib package and I could build HDF5.
Looking forward for your help...
