### ISSUE TITLE
HDF5 module crash when call the function dsread

### ISSUE THREAD

**Issue by stereomatchingkiss** [Itseez/opencv_contrib#552]
In short, following function will crash

```
virtual void cv::hdf::HDF5::dsread 	( OutputArray  	Array,
       		                                          String  	dslabel,
                                                	  const int *  	dims_offset 
	                                                ) const
```

Because, it will called it self recursive

```
// overload
void HDF5Impl::dsread( OutputArray Array, String dslabel,
             const int* dims_offset ) const
{
    dsread( Array, dslabel, dims_offset);
}
```

Maybe the thing you want to do is

```
// overload
void HDF5Impl::dsread( OutputArray Array, String dslabel,
             const int* dims_offset ) const
{
    dsread( Array, dslabel, dims_offset, NULL);
}
```

However, without specify count, this function will read as much data into Array as possible

**Comment by cbalint13** [comment]
@stereomatchingkiss ,

* That was ment as overloaded call.
* Will fix within https://github.com/Itseez/opencv_contrib/pull/547 right today.

 Thank you for spotting that ! I am working on test cases (at least to proof examples in the docs) and on noncontinous Mat (using hdf stride over hyperslabs.

**Comment by cbalint13** [comment]
@stereomatchingkiss ,

* It was ment to fix within PR https://github.com/Itseez/opencv_contrib/pull/480 , but in the case of dsread() it was a clear miss.

Fixed it now, I hope proper testcases with end of any latent bugs.

**Comment by stereomatchingkiss** [comment]
Thanks for the fix, so fast.
