### ISSUE TITLE
Make enum and typedef of TypeDepth become public

### ISSUE THREAD

**Issue by stereomatchingkiss** [Itseez/opencv_contrib#558]
Why making the depth and value_type of TypeDepth  as private data member?If they are private, user cannot access them. Should we make them become public?

**Comment by alalek** [comment]
What module?

**Comment by Aravind-Suresh** [comment]
I think its in OpenCV module, not contrib.
https://github.com/Itseez/opencv/blob/master/modules/core/include/opencv2/core/traits.hpp

Should we make them public? If yes, I will fix it.

**Comment by stereomatchingkiss** [comment]
>I think its in OpenCV core module, not contrib.

Yap, it is core module. I would like to add more type into it too(ex : CV_8UC2, CV_8UC3 etc)

**Comment by stereomatchingkiss** [comment]
>I think its in OpenCV core module, not contrib.

Yap, it is core module. I would like to add more type into it too(ex : CV_8UC2, CV_8UC3 etc)

**Comment by stereomatchingkiss** [comment]
>I think its in OpenCV core module, not contrib.

Yap, it is core module. I would like to add more type into it too(ex : CV_8UC2, CV_8UC3 etc)

**Comment by alalek** [comment]
Type depth should not contain channels information (by design).
You should use `CV_MAKE_TYPE(CV_8U, 2)` instead or just `CV_8UC2` macro.

BTW, this is wrong place for questions like this. Use http://answers.opencv.org
Only bugs should be filled here.
