### ISSUE TITLE
Using the dnn sample get a bug

### ISSUE THREAD

**Issue by jackcc** [Itseez/opencv_contrib#576]
when i use the sample caffe_googlenet.cpp I get a error,#136,the forward func,
when run the layerInstance = LayerFactory::createLayerInstance(type, params);i got a null ptr, the error is OpenCV Error: Unspecified error (Can't create layer "conv1/7x7_s2" of type "Convolution") in cv::dnn::LayerData::getLayerInstance, file E:\opencv_contrib-3.1.0\modules\dnn\src\dnn.cpp, line 122,so if who can give me some help, deeply grateful.

btw,I use vs2013 and win10.

**Comment by kawaikawai** [comment]
add following line at the beginning of main function.

cv::dnn::initModule();
