### ISSUE TITLE
calcHist() works for ushort but this is not documented

### ISSUE THREAD

**Issue by drtimes** [Itseez/opencv_contrib#585]
[Documentation](http://docs.opencv.org/3.0-beta/modules/imgproc/doc/histograms.html) for OpenCV 3.0 states that calcHist() function takes as input arrays of depths CV_8U or CV_32F. But from [source code  in OpenCV 3.1.0](https://github.com/Itseez/opencv/blob/debe99f1a4cc0ea859b91996613934e361b544b6/modules/imgproc/src/histogram.cpp#L1350) it seems the function can be used for 16-bit arrays. I tried and it works just fine. It would be great if you documented the feature.

16-bit image [sample_image.zip](https://github.com/Itseez/opencv_contrib/files/175833/sample_image.zip)

```
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include <opencv/cv.h>

using namespace cv;

int main(int argc, char *argv[])
{
        Mat img = imread("out1.tif", IMREAD_UNCHANGED);

        if (img.depth() == CV_16U)
        {
            int histSize = 2048;
            float range[] = {0, histSize};
            const float* histRange = { range };
            bool uniform = true; bool accumulate = false;

            Mat hist;
            calcHist( &img, 1, 0, Mat(), hist, 1, &histSize, &histRange, uniform, accumulate );

            double hmin, hmax;
            minMaxLoc(img, &hmin, &hmax);

            //plot the histogram
            Mat canvas = Mat::zeros(200, histSize, CV_8UC1);
            for (int j = 0, rows = canvas.rows; j < histSize-1; j++)
                line(canvas, Point(j, rows), Point(j, rows - (hist.at<float>(j) * rows/hmax)), Scalar(255,0,0));

            imshow("hist", canvas);
            waitKey(0);
        }
        else
            return 1;

        return 0;
}
```

**Comment by mshabunin** [comment]
This issues should be posted to the [main repository issue tracker](https://github.com/Itseez/opencv/issues).
