### ISSUE TITLE
Cannot compile with HDF on Ubuntu Vivid and above

### ISSUE THREAD

**Issue by vrabaud** [Itseez/opencv_contrib#588]
This is normal as the headers have changed in newer versions of hdf5.
Before, you have /usr/include/hdf5.h (cf http://packages.ubuntu.com/trusty/amd64/libhdf5-dev/filelist).
In vivid and above, you have: /usr/include/hdf5/serial/hdf5.h (cf http://packages.ubuntu.com/vivid/amd64/libhdf5-dev/filelist)

Example of error here: http://build.ros.org/job/Kbin_uW64__opencv3__ubuntu_wily_amd64__binary/1/console

This is a duplicate of https://github.com/Itseez/opencv/issues/6296 but for opencv_contrib.

I believe this is for @cbalint13

**Comment by cbalint13** [comment]
@vrabaud ,

Uhh, first I try describe the picture by having in mind some ideas how to fix it but aslo require @alalek 's opionion too.

**(1)** HDF5 detection in opencv_contrib is based on **cmake's** internal FindHDF5 module (outside opencv), which is preferred and requires zero maintenance over time, see:
* https://github.com/Itseez/opencv_contrib/blob/master/modules/hdf/CMakeLists.txt#L19

**(2)** I don't understand why debian releng want's to unconform with  ``` /usr/include/hdf5/serial/hdf5.h``` , probably they have strong reasons.  But how they managed then their other packages to lookup in proper path ?! I am not used with Debian land and have more experience with redhat products.

**(3)** Worse is that cmake's module is not flexible enough to accept some kind of HINT paths, even FindHDF5.cmake from hdf5 package lacks such things. It would be an easy workaround to pass something like HDF5_INCLUDE_DIRS a HINT.

**(4)** Possible solution is to add our own FindHDF5.cmake to opencv but would be hard to maintain it in time, especially if upstream changes something. BTW, even original HDF5's FindHDF5.cmake shipped is quite broken, on MS-WIN we needed to workaround it last time with local things like:
* https://github.com/Itseez/opencv_contrib/blob/master/modules/hdf/CMakeLists.txt#L3

**(5)** In my opinion we would perhaps need to PR against cmake upstream instead.

I wonder what @alalek would say, last time we tackle quite in length on HDF5&cmake lands: https://github.com/Itseez/opencv_contrib/pull/547

**(6)** I don't know, other ideas ?


**PS:**
 For opencv flann module I would remove out the hdf5 part (quite primitive one) which looks like some redundant feature in a module that is about neighbour searches not about file i/o.

**Comment by cbalint13** [comment]
@vrabaud , @alalek 

I think this explain our issue: https://cmake.org/Bug/view.php?id=15618 , as mentioned at **(5)**.

**Comment by vrabaud** [comment]
actually, things work after d766663add331bbec49f6dfbd5dee45966bbc34b
The version I was using was anterior, so master is fine I guess.
As long as hdf5.h is not in the public interface, we are fine it seems. Closing this one as 3.2.0 will have the fix.

**Comment by vrabaud** [comment]
Proof that it works: http://build.ros.org/job/Kbin_uW64__opencv3__ubuntu_wily_amd64__binary/4/
Sorry for the noise, thx for listening.
