### ISSUE TITLE
When updating cmake building failed 

### ISSUE THREAD

**Issue by xning** [Itseez/opencv_contrib#589]
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencv3/3.1.0_2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VER
Last 15 lines from /Users/nano/Library/Logs/Homebrew/opencv3/01.cmake:
-- Found JNI: /System/Library/Frameworks/JavaVM.framework  
-- Could NOT find Matlab (missing:  MATLAB_MEX_SCRIPT MATLAB_INCLUDE_DIRS MATLAB_ROOT_DIR MATLAB_LIBRARIES MATLAB_LIBRARY_DIRS MATLAB_MEXEXT MATLAB_ARCH MATLAB_BIN) 
CMake Error at /usr/local/Cellar/vtk/7.0.0/lib/cmake/vtk-7.0/vtkModuleAPI.cmake:120 (message):
  Requested modules not available:

    vtkRenderingOpenGL
Call Stack (most recent call first):
  /usr/local/lib/cmake/vtk-7.0/VTKConfig.cmake:88 (vtk_module_config)
  cmake/OpenCVDetectVTK.cmake:6 (find_package)
  CMakeLists.txt:597 (include)

-- Configuring incomplete, errors occurred!
See also "/tmp/opencv320160319-2367-1yj0x7s/opencv-3.1.0/macbuild/CMakeFiles/CMakeOutput.log".
See also "/tmp/opencv320160319-2367-1yj0x7s/opencv-3.1.0/macbuild/CMakeFiles/CMakeError.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-science/issues

**Comment by alalek** [comment]
Should be fixed in the latest master: https://github.com/Itseez/opencv/pull/5893

**Comment by tinnted** [comment]
i also got the same error , if you dont need VTK then add -DWITH_VTK=OFF to the cmake
because building master gets another error with cuda 8.0 which has no fix yet  #6728

**Comment by tinnted** [comment]
you can either add -DWITH_VTK=OFF to the cmake command or as i did copy the VTK cmake detect file from master to 3.1
