### ISSUE TITLE
There is not java folder in opencv/platforms/build_android_arm/install/sdk

### ISSUE THREAD

**Issue by nannanmath** [Itseez/opencv_contrib#617]
I use this tutorial https://github.com/alexkarargyris/Caffe_OpenCV_Android_App and opencv with opencv-contrib can be compiled successfully, but I can not find the java folder in opencv/platforms/build_android_arm/install/sdk, there are etc and native folders only.

**Comment by alalek** [comment]
Check CMake output:
```
--   OpenCV modules:   ... java ...
     ...
--   Java:
--     ant:                         /usr/local/bin/ant (ver 1.9.4)
--     Java wrappers:               YES
--     Java tests:                  YES
```

And run `make install` (don't use sudo) if all is fine in CMake

**Comment by nannanmath** [comment]
I find all of them are NO. Could you tell me how to solve it? If I need to install something? Thanks!

**Comment by mshabunin** [comment]
You need to install JDK and ant in case to build java wrappers for OpenCV. You can find more hints in [this tutorial](http://docs.opencv.org/master/d9/d52/tutorial_java_dev_intro.html#gsc.tab=0).
