### ISSUE TITLE
ximgproc: SLIC out of bounds

### ISSUE THREAD

**Issue by berak** [Itseez/opencv_contrib#623]
```
#include <opencv2/opencv.hpp>
#include <opencv2/ximgproc.hpp>
using namespace cv;
using namespace cv::ximgproc;

int main(int argc, char **argv)
{
    Mat image = imread("im/lena.png"); //512x512
    Ptr<SuperpixelSLIC> slic = createSuperpixelSLIC(image, SLICO, 10, 10.0f) ;
    return 0;
}
```

breaks [here](https://github.com/Itseez/opencv_contrib/blob/master/modules/ximgproc/src/slic.cpp#L436) , m_numlabels=2621, m_kseedsx.size()=2601

actually, it works, when choosing a larger region, like 12

for context, see [here](http://answers.opencv.org/question/91790/slic-error/)

**Comment by cbalint13** [comment]
@berak ,

* Will look into this.

**Comment by cbalint13** [comment]
@berak ,

- All fine on my side (git master latest).
- Could check and run this sample:  http://openrisc.rdsor.ro/berak.tar.bz2 ?

Let me know the results.

**Comment by cbalint13** [comment]
@berak ,
* Looking in more details (MSVC), seems linux to be fine.

**Comment by cbalint13** [comment]
@berak ,

* Can check this patch ?

```
--- opencv_contrib/modules/ximgproc/src/slic.cpp	2015-12-23 11:30:53.359563158 +0200
+++ opencv_contrib/modules/ximgproc/src/slic.cpp	2016-04-05 17:31:29.774349783 +0300
@@ -226,11 +226,12 @@
     else
       CV_Error( Error::StsInternal, "No such algorithm" );
 
+    // update amount of labels now
+    m_numlabels = (int)m_kseeds[0].size();
+
     // perturb seeds given edges
     if ( perturbseeds ) PerturbSeeds( edgemag );
 
-    // update amount of labels now
-    m_numlabels = (int)m_kseeds[0].size();
 }
 
 void SuperpixelSLICImpl::iterate( int num_iterations )
```

- m_numlabels is estimated at: https://github.com/Itseez/opencv_contrib/blob/master/modules/ximgproc/src/slic.cpp#L204
- m_numlabels must be updated atfer: https://github.com/Itseez/opencv_contrib/blob/master/modules/ximgproc/src/slic.cpp#L223
- m_numlabels must agree m_kseeds{x,y}.size before enter: https://github.com/Itseez/opencv_contrib/blob/master/modules/ximgproc/src/slic.cpp#L230

**Comment by berak** [comment]
Köszönöm szépen !
(Vielen dank !)

yes, demo code + patch are working nicely now.

**Comment by berak** [comment]
incredibly fast ! thanks again.
