### ISSUE TITLE
selectROI("tracker", frame, objects)  cannot work

### ISSUE THREAD

**Issue by nuli0355** [Itseez/opencv_contrib#635]
I used the latest code,and when I press the ESC key,there is no response？

...
	// get bounding box
	cap >> frame;
	selectROI("tracker", frame, objects);
	//quit when the tracked object(s) is not provided
	if (objects.size()<1)
		return 0;
	// initialize the tracker
	trackers.add(frame, objects);
...

**Comment by sturkmen72** [comment]
> "Select an object to track and then press SPACE or ENTER button!" 
> "Finish the selection process by pressing ESC button!"
did you press SPACE or ENTER ?
