### ISSUE TITLE
haarcascade_mcs_eyepair_small.xml

### ISSUE THREAD

**Issue by sturkmen72** [Itseez/opencv_contrib#644]
Test code

```

#include <iostream>

#include "opencv2/highgui.hpp"
#include "opencv2/objdetect.hpp"
#include "opencv2/imgproc.hpp"

using namespace std;
using namespace cv;

int main( int argc, const char** argv )
{
   	if (argc < 3)
    {
    cerr << "usage:\n" << argv[0] << " <image_file_name> <model_file_name>" << endl;
    return 0;
    }

    // Read in the input arguments
    string model = argv[2];

    CascadeClassifier detector(model);
    if(detector.empty())
    {
        cerr << "The model could not be loaded." << endl;
    }

    Mat current_image, grayscale, equalize;

    // Read in image and perform preprocessing
    current_image = imread(argv[1]);
    cvtColor(current_image, grayscale, CV_BGR2GRAY);
    equalizeHist(grayscale,equalize);

    vector<Rect> objects;
    detector.detectMultiScale(equalize, objects, 1.05, 1);

    for(int i = 0; i < objects.size(); i++)
    {
        rectangle(current_image, objects[i], Scalar(0, 255, 0),2);
    }

    imshow("result",current_image);
    waitKey();
    return 0;
}

```
calling this code like `testcode oscarSelfie.jpg haarcascade_mcs_eyepair_small.xml` gives bad output like

![result_current](https://cloud.githubusercontent.com/assets/12151541/14764650/a085cf64-09c8-11e6-964b-7109178ce510.png)

result of another `haarcascade_mcs_eyepair_small.xml` ( i found it on my computer, don't remember from where i get it )

![result_new](https://cloud.githubusercontent.com/assets/12151541/14764666/75798846-09c9-11e6-872b-87a4c9baa1ed.png)

**Comment by StevenPuttemans** [comment]
Ow can you see how your metadata says that the image is oriented? OpenCV reads that data now since a month or 5 and thus interprets the landscape/portrait mode

**Comment by sturkmen72** [comment]
i think the problem is here.

```
<cascade type_id="opencv-cascade-classifier"><stageType>BOOST</stageType>
  <featureType>HAAR</featureType>
  <height>22</height>
  <width>5</width>
```

https://github.com/Itseez/opencv_contrib/blob/master/modules/face/data/cascades/haarcascade_mcs_eyepair_small.xml#L124-L125

 maybe there is a bug on the code for creating or converting cascade-classifier

**Comment by StevenPuttemans** [comment]
The problem is not in the model, else the detections wont be similar except for the rotation. Its a problem when drawing. I will cook up some code to prove it tomorrow!

**Comment by StevenPuttemans** [comment]
Ow wait, let me get back on this. I indeed misread those lines. Afaik all the models had wrong height and width dimensions and they were adjusted, but this one is clearly wrong. Let me do some tests and get back to you!

**Comment by StevenPuttemans** [comment]
Ok so I just downloaded the first oscarselfie image from google, first hit (https://pbs.twimg.com/media/BhxWutnCEAAtEQ6.jpg). Then did the code with the `haarcascade_mcs_eyepair_small.xml`. This gave me the following result

![screenshot from 2016-05-03 13 02 23](https://cloud.githubusercontent.com/assets/4621239/14981424/58a20c8a-112f-11e6-9143-eeb95ed550ff.png)

however this model can only be found in the 2.4 repository... so there is probably a license reason why it is not in OpenCV3?

But as you see it works just fine here....

**Comment by StevenPuttemans** [comment]
Also this issue should be at the main opencv repo I guess...

**Comment by sturkmen72** [comment]
i tried to change the file ( swap height width values ) manually like 

```
<cascade type_id="opencv-cascade-classifier"><stageType>BOOST</stageType>
  <featureType>HAAR</featureType>
  <height>5</height>
  <width>22</width>
```

it works well

**Comment by StevenPuttemans** [comment]
BUT listen to me ... the MODEL at the [current 2.4 ](https://github.com/Itseez/opencv/blob/2.4/data/haarcascades/haarcascade_mcs_eyepair_small.xml)head works perfectly fine ... you must be using an old version ...

**Comment by StevenPuttemans** [comment]
OH WAIT i finally discovered the problem

1) A half year ago these models broke down.
2 ) They got updated inside the main data repository, but NOT inside the face module.

So my suggestion, please grab the models from 2.4 branch, the opencv/data/haarcascade folder and replace the once in the face repo here.

**Comment by StevenPuttemans** [comment]
Reason BTW is as explained, the models contain a non BSD license and can thus NOT be inside the main OpenCV repo following the guidelines.

**Comment by sturkmen72** [comment]
the file is here : https://github.com/Itseez/opencv_contrib/tree/master/modules/face/data/cascades 

i think we should replace it with old one or make correct

**Comment by StevenPuttemans** [comment]
Like just said by me, do fix it, but rather replace it by the working models of the 2.4 branch

**Comment by StevenPuttemans** [comment]
To keep consistency in my opinion :D Or supply your small fix. One or the other will work I guess.

**Comment by sturkmen72** [comment]
OK. thanks for your help to uncover the problem.

**Comment by StevenPuttemans** [comment]
You are welcome :+1:
