### ISSUE TITLE
Java wrappers for structured_light module cannot be generated

### ISSUE THREAD

**Issue by dharezlak** [Itseez/opencv_contrib#652]
An attempt to generate Java wrappers for the `structured_light` module by appending `WRAP java` to the `structured_light/CMakeLists.txt` file fails with the following error:
```
opencv-3.1.0/build/src/org/opencv/structured_light/GrayCodePattern.java:34: error: method create() is already defined in class GrayCodePattern
    [javac]     public static GrayCodePattern create()
    [javac]                                   ^
Linking CXX executable ../../bin/opencv_test_structured_light
    [javac] 1 error
Target 'jar' failed with message 'Compile failed; see the compiler error output for details.'.
```
Are there any guidelines on how to write OpenCV module API so that Java wrapping works well? I would like to test the module from Java.
Also, the generated Java `create` method does not have any parameters while in the C++ code the method takes one parameter: `GrayCodePattern::Params &parameters = GrayCodePattern::Params()`.

**Comment by berak** [comment]
can you try if [this works](https://github.com/berak/opencv_contrib/tree/structured_light_py_java) ?

**Comment by dharezlak** [comment]
The cause of the linking problem is wrong package naming in the `structured_light.cpp` file. According to https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/design.html#resolving_native_method_names underscore characters should be replaced with `_1` in the native method signatures. In this case `structured_light` part of the package was not properly escaped resulting in native methods such as `JNIEXPORT jboolean JNICALL Java_org_opencv_structured_light_StructuredLightPattern_generate_10` instead of `JNIEXPORT jboolean JNICALL Java_org_opencv_structured_1light_StructuredLightPattern_generate_10` (though the mehod name itself is correct).

**Comment by berak** [comment]
it seems, [this is already done for the class name](https://github.com/Itseez/opencv/blob/master/modules/java/generator/gen_java.py#L1431), but probably needs same tratment for the module name there. again, i cannot test, but maybe changing l. 1431 to:

    module = self.module.replace('_', '_1'), \

simply does the trick. (and then, it needs another pr in main opencv for this)

**Comment by dharezlak** [comment]
After applying the above modification (only line 1431) and building from scratch the linking problem is gone entirely so I guess a pull request is in order. Thank you for the support.

**Comment by berak** [comment]
@dharezlak , nice to hear that.

would you like to takeover the pr now ? (also the nessecary changes to gen_java.py in opencv main)
