### ISSUE TITLE
model filename for structured_edge_detection

### ISSUE THREAD

**Issue by sushruta** [Itseez/opencv_contrib#654]
[structured_edge_detection program](https://github.com/Itseez/opencv_contrib/blob/master/modules/ximgproc/samples/structured_edge_detection.cpp#L52) seems to take a model filename as input. Where can I find this file? The original implementation of the paper - https://github.com/pdollar/edges has a model but it's a matlab `.mat` file and I'm not sure what to do of it.

Any help or pointers would be greatly appreciated. thanks!

**Comment by StevenPuttemans** [comment]
A small google search led me to [this SO topic](http://stackoverflow.com/questions/33317152/model-file-for-opencvs-structured-edge-detector) telling you that the opencv extra repo has the [necessary data](https://github.com/Itseez/opencv_extra/blob/master/testdata/cv/ximgproc/model.yml.gz) for testing the sample.

I guess it could be added more clearly to the sample! I will add an extra description through a PR.

**Comment by StevenPuttemans** [comment]
There you go!

**Comment by sushruta** [comment]
thanks a lot. This helps a lot
