### ISSUE TITLE
ArUco runtime error at the end of the program

### ISSUE THREAD

**Issue by eladj** [Itseez/opencv_contrib#662]
I've compiled opencv 3.1 with the latest opencv-contrib sources on Windows 7 32-bit Visual Studio 2013.
The ArUco module crashes at the end of the program.
I've narrowed down the problem to this minimal program:

```c++
#include "stdafx.h"
#include "opencv2\opencv.hpp"
#include "opencv2\aruco.hpp"

int _tmain(int argc, _TCHAR* argv[])
{
	cv::aruco::Dictionary arucoDict = cv::aruco::getPredefinedDictionary(cv::aruco::DICT_ARUCO_ORIGINAL);
	cv::aruco::DetectorParameters detectorParams;
	cv::Ptr<cv::aruco::Dictionary> pArucoDict = &arucoDict;
	cv::Ptr<cv::aruco::DetectorParameters> pDetectorParams = &detectorParams;
	return 0;
}
```

The lines with the `cv::Ptr<...>` cause the problem.
I'm getting this message in debug:

![image](https://cloud.githubusercontent.com/assets/5568883/15045621/392f0392-12e4-11e6-8729-8ab96688f7c3.png)

Looks like some bug while freeing memory...

**Comment by alalek** [comment]
`cv::Ptr<>` can be initialized from variables on heap only (you allocate them on stack)
