### ISSUE TITLE
Error occured when choose "Build_opencv_world" in the GUI Cmake

### ISSUE THREAD

**Issue by luxl** [Itseez/opencv_contrib#704]
VS 2015 wil reminds you that can't find "opencv2\xfeatures2d\nonfree.hpp". But if I don't choose "Build_opencv_world", it is fine. But I think it is more convenient to use "opencv_world". By the way I'm using OpenCV 3.1. And it seems that the "contrib_wold" hasn't been finished yet.

**Comment by LaurentBerger** [comment]
I have got something different with VS 2013 and opencv 3.1 (http://answers.opencv.org/question/81000/build-opencv-31-world-with-opencv-contrib/). Result is same and i don't use opencv_world
