### ISSUE TITLE
opencl_kernels_xfeatures2d.cpp not found when compile with CUDA

### ISSUE THREAD

**Issue by KKyang** [Itseez/opencv_contrib#91]
When choose to compile with CUDA 6.5, cmake in gui will ask for opencl_kernels features2d.cpp cause the visual studio solution fail to build.

**Comment by StevenPuttemans** [comment]
@mshabunin this can also be closed down - it is known that the world module does not build stable on each possible configuration but the wide range of possibilities for that is probably due to an underlying module not building.
